### ISSUE TITLE
Extension as vector of ClientEncryptedSNI structures

### ISSUE THREAD

**Issue by roelfdutoit** [tlswg/draft-ietf-tls-esni#103]
Please consider changing the ESNI client extension to a vector of ESNI values.  This could be used for server-side redundancy and key rollover.  I understand that only one of the entries would be ack'd in EE, and that we would have to think through the possible attacks on the mechanism due to the change.

**Comment by chris-wood** [comment]
@roelfdutoit can you please bring this issue to the list for further discussion?
