### ISSUE TITLE
Use ESNI RRType instead of TXT

### ISSUE THREAD

**Issue by mcmanus** [tlswg/draft-ietf-tls-esni#109]
PR #73 from @ghedo implements the ESNI RRType, but there doesn't seem to be another issue currently open to track discussion of it.

* a new RRType allows the removal of the _esni prefix (#105 and #79)
* reusing TXT has the potential for conflicts with other uses even with the prefix. (imagine the definition of a TXT record that simply applied to all DNS entries)
* while both TXT and ESNI are 8 bit clean, some people are surprised to learn that about TXT so using a new type may be more robust. Some generic tools processing TXT records would benefit from this.
* TXT is a set of  <= 255 byte strings, defining a new type removes that complexity and reduces overhead
* There was initially concern about the viability of new RRTypes, but I believe people are more comfortable with that now than when the text was drafted.

**Comment by chris-wood** [comment]
Fixed in #144.
