### ISSUE TITLE
ESNIInclude

### ISSUE THREAD

**Issue by mcmanus** [tlswg/draft-ietf-tls-esni#110]
issues #105 and #79 advocate for the removal of the _esni prefix.

A significant side effect of that is that it becomes impossible to use a CNAME at the apex of a zone in order to refer to ESNIKeys of a server operated elsewhere. Inlining keys, as is often done with A/AAAA at the apex, is not plausible due to key rotation.

The issue can largely be mitigated with the introduction of an inclusion mechanism directly in the TXT/ESNI record.

**Comment by chris-wood** [comment]
This should be fixed by #136 and follow up changes. Closing as such. Please reopen if necessary!

**Comment by mcmanus** [comment]
I don't believe #136 resolves this.

136 effectively requires the address and ESNI information to be stapled together (which I still find objectionable). The issue here is that the apex cannot use a CNAME to delegate to the actual third party provider's ESNI record.. typically it just includes an A/AAAA record at the apex and hopes the pointer doesn't go stale. That's bad enough for A/AAAA but it would be terrible for ESNI because it means copying keying information and hoping it doesn't go stale between two different entities.

@chris-wood can you reopen?

**Comment by chris-wood** [comment]
Sure! Sorry for the misunderstanding. We can probably update this PR to make use of the new DNS-specific extensions.

**Comment by chris-wood** [comment]
Fixed by #187.
