### ISSUE TITLE
Compress server name in ClientHello

### ISSUE THREAD

**Issue by kazuho** [tlswg/draft-ietf-tls-esni#116]
In a large-scale server deployment that benefits the most from ESNI (due to the size of the umbrella under which you would hide the domain names), it is often the case that the largest length of the server name to be supported is *unknown*. That leads such server deployments to use a padded_length of 260 because the longest valid DNS name is 253 characters, bloating the ClientHello.

It is beneficial to apply a lightweight compression algorithm to the server name to reduce the overhead.

Some points to consider:
* We cannot use a pre-learnt dictionary, because what we care is the longest possible length. Compression algorithm using a pre-learnt dictionary assigns longer symbols for rarely used patterns, which means that the worst case is longer than the non-compressed string.
* We can use an adaptive compression algorithm (e.g. lz77, brotli), however they also would not compress well if the server-name is a random-looking string.

**Comment by kazuho** [comment]
Considering the two points, one practical solution will be to map the valid characters of a DNS name (i.e. `a`-`z`,`0`-`9`,`.`,`-`,`_`) to a integer between 0 to 38, and encode three characters into a 16-bit value.

By applying the conversion, the worst length changes from 253 to 169 (i.e. `ceil(253/3*2)`), giving us 84 bytes back.

**Comment by kazuho** [comment]
To put it another way, the entropy we have when the set of server names is unknown is 39<sup>253</sup> ~ 256<sup>167.2</sup>.

I do not think that we can go far below this limit by using contexts between the characters, because there aren't many patterns that are forbidden (two consecutive dots is (possibly one of the) rare pattern that never appears).

Considering that, using `mod 39` to squeeze three characters into 16 bit to achieve 256<sup>169</sup> is reasonable.

**Comment by kontaxis** [comment]
The valid characters in a DNS host name are [a-zA-Z0-9-] so 63.

**Comment by chris-wood** [comment]
@kazuho how do you want to proceed here?

**Comment by kazuho** [comment]
@chris-wood I think we should close this with no action.

**Comment by chris-wood** [comment]
Sounds good! Closing.
