### ISSUE TITLE
record_digest input bytes

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#119]
The I-D says: "record_digest : A cryptographic hash of the ESNIKeys structure from which the ESNI key was obtained, i.e., from the first byte of "checksum" to the end of the structure. This hash is computed using the hash function associated with suite."

From looking at the NSS code it appears that the record_digest input is actually the entire ESNIKeys (after base64 decode) including the version and checksum. Is that correct?

IOW, does the following also produce the right value (for CF and sha256)?

``dig +short txt _esni.www.cloudflare.com  | sed -e 's/"//g' | base64 -d | openssl sha256``

**Comment by chris-wood** [comment]
#163 proposes removing the checksum, which should clear this up.

**Comment by chris-wood** [comment]
Closing since #163 landed. @sftcd, please re-open if this is still an issue!
