### ISSUE TITLE
Can the ESNI values change upon HRR?

### ISSUE THREAD

**Issue by kazuho** [tlswg/draft-ietf-tls-esni#121]
RFC 8446 requires us to specify if the contents of ESNI can change upon a HRR.

In case of ESNI, the payload of the extension obviously can change, because the AAD (i.e. ClientHello.KeyShareClientHello) can change. However, we haven't specified if other values (e.g., ClientESNIInner.nonce) can.

IMO, we should prohibit needless changes.

To clarify, all the non-encrypted portion and the encrypted payload of ESNI MUST be consistent between the first ClientHello and the second one.

**Comment by ekr** [comment]
👍

**Comment by jb-wisemo** [comment]
Bad idea.  Causing the encrypted ESNI to change such that observers cannot determine if this is a request for the same or a different back end name is a major security feature of the mechanism.  If a popular CDN such a cloudflare or S3 enables ESNI on their front end servers, observers should not be able to detect if repeated requests from a client are the usual pattern of retrieving common noise from web frameworks, random surfing of many sites or a long visit to a banned site.  ESNI servers (and only ESNI servers) would deal with recognizing that requests are actually resuming the same session despite the camouflage differences.

**Comment by kazuho** [comment]
@jb-wisemo 
> Causing the encrypted ESNI to change such that observers cannot determine if this is a request for the same or a different back end name is a major security feature of the mechanism.

I do not get that. When HRR is used on TCP, the fact that the 1st CH and 2nd CH (sent in HRR) specify the same server name will be evident from the fact that they are sent on a single TCP connection. In case of HRR used with cookies, an observer will be able to track the pair by using cookies.

**Comment by chris-wood** [comment]
This is addressed in #207.

**Comment by chris-wood** [comment]
Fixed by #207.
