### ISSUE TITLE
Encrypted nonce in ClientESNIInner

### ISSUE THREAD

**Issue by roelfdutoit** [tlswg/draft-ietf-tls-esni#123]
Would you consider a PR for encrypting the ClientESNIInner nonce?

What I have in mind is the following:
`struct {
       EncryptedNonce enc_nonce;
       PaddedServerNameList realSNI;
   } ClientESNIInner;`
.. where:
`nonceAAD = ClientHello.KeyShareClientHello || realSNI`
`EncryptedNonce = AEAD-Encrypt(nonce_key, nonce_iv, nonceAAD, nonce)`
.. and:
`nonce_key = HKDF-Expand-Label(Zx, "nonce key", Hash(ESNIContents), key_length)`
`nonce_iv = HKDF-Expand-Label(Zx, "nonce iv", Hash(ESNIContents), iv_length)`

The use case is an escrow system where the client wants to allow **read-only** visibility of the real SNI value by only sharing {key,iv} and keeping {nonce_key,nonce_iv} and Zx secret.   Only the real server would be able to acknowledge 'nonce' in EncryptedExtensions.

**Comment by ekr** [comment]
This seems like a change which is very hard to analyze with limited value,
so I would not be in favor.

**Comment by roelfdutoit** [comment]
PR created:
https://github.com/tlswg/draft-ietf-tls-esni/pull/147

**Comment by DavidSchinazi** [comment]
Hi @roelfdutoit, can you elaborate on the motivations for this change? In what scenario would the client wish to share the SNI with a third party?

**Comment by roelfdutoit** [comment]
Enterprise network security solutions are evolving, especially in the area of monitoring and analytics, and SNI is a valuable attribute in such an environment.  A client would share the ESNI {key,iv} with configured enterprise monitoring devices (NGFW, IPS, Proxy, IDS, DLP, etc) and this becomes critical in a zero trust network.  There is a lot of focus on using ESNI in a CDN world, but the mechanism would also be very valuable for enterprises that host multiple proprietary services - again, in a zero trust environment.  Those proprietary services and applications must be monitored at different points in the enterprise network, requiring access to the true SNI.  The PR would provide a responsible way to share the true SNI, without the need for traditional TLS intercept - assuming a secure sharing mechanism is used.

**Comment by chris-wood** [comment]
@roelfdutoit can you please bring this issue to the list for further discussion?
