### ISSUE TITLE
Consider dropping split mode altogether

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#130]
The mechanism to make split mode work in practice requires non-trivial changes to both the fronting server and origin. Moreover, as the main (mass user base) benefit for ESNI is shared mode, perhaps we should consider dropping split mode.

**Comment by ekr** [comment]
I would not be in favor of this change. There are real uses for split mode and we should try to address them

**Comment by DavidSchinazi** [comment]
I'm in favor of removing split mode from this draft, the added complexity is not necessarily worth it.

**Comment by bemasc** [comment]
I thought about this some and decided that:
 * Split mode is valuable and worth supporting.
 * It needs more specification than can reasonably fit in this draft.
 * It's part of a larger problem related to load balancers.

So I wrote a [new draft on this topic](https://tools.ietf.org/html/draft-schwartz-tls-lb-00).  My hope is that we can remove the detailed discussion of split mode here and replace it with a reference to that draft.

There's one thing I'd like to resolve before sending that draft to the TLS list: That draft is derived from the brief proposal in this draft to use a PSK to transfer `Z` between the servers.  I'm not 100% sure who proposed that design, but in my draft I added an acknowledgement to @ekr after looking through the version history here.  I'd like to make sure that credit is correct, and I'm happy to add whoever came up with that to the authors list.

**Comment by ekr** [comment]
1. I am not in favor of removing the discussion of split mode from this
document, though I am fine to have detail elsewhere.
2. I think I was the person who proposed the PSK idea, but honestly, it's
pretty obvious so I'm not worried about credit and if someone else thinks
they were first, I'm not going to argue,

**Comment by davidben** [comment]
One discrepancy is whether the frontend shares the Z value with the backend or the ClientESNIInner. The new draft says the latter and the appendix in the ESNI draft says the former.

Was there a particular reason to send Z? All else equal, ClientESNIInner seems much more straightforward to deploy and reason about. Frontend and backend do not need to coordinate on which ESNI encryption schemes to support if sending Z. It also feels odd to send along a raw unKDFed key exchange secret like that, but maybe it's fine?

**Comment by ekr** [comment]
I suggested Z on the theory that it would make it hard to lie about
ClientESNIInner. I haven't thought through it all in detail, though.

**Comment by chris-wood** [comment]
(Late filling this out...)

Discussed in Montreal: we don't need to remove it -- we simply shouldn't make it impossible to implement.
