### ISSUE TITLE
Proposal: ESNI record Implies TLS support

### ISSUE THREAD

**Issue by bemasc** [tlswg/draft-ietf-tls-esni#131]
Proposal:
The ESNI DNS record specification, wherever it ends up, should have the following requirement:
"If a domain or endpoint publishes an ESNI DNS record, then that domain MUST be accessible over TLS."

This is almost trivial (why would you publish an ESNI record if you don't have TLS support?), but it would be tremendously useful for browsers, as a way to learn that the specified domain supports HTTPS before attempting a connection.  If DNS records are fetched over a secure channel, this would enable HSTS-like behavior without an insecure bootstrap or a preload list.

**Comment by DavidSchinazi** [comment]
A domain name that has ESNI keys is very likely to support TLS, but you can't assume that is supports HTTPS on port 443 - they could be using TLS for something else.

**Comment by bemasc** [comment]
That depends on how we define the ESNI record.  For example, we could insert a port in the name (like SRV), or include a list of the applicable ports in the record contents.  (Or we could just declare that ESNI implicitly blacklists port 80, which I believe is what you are arguing against.)

It's up to us.

**Comment by kazuho** [comment]
By default, http and https are different origins. HSTS is a opt-in signal that changes the behavior. 

Considering that, I think that the discussion needs to happen the HTTPbis WG on if the WG should define an extension to ESNI.

**Comment by martinthomson** [comment]
Is ESNI something you would use for protocols other than HTTP?

**Comment by ekr** [comment]
I tend to think yes. Suppose, for instance, you had DoQ.

**Comment by chris-wood** [comment]
Agreed. @bemasc, this should probably go to httpbis for discussion! I'm closing for now.
