### ISSUE TITLE
Extensible information in ESNIKey DNS record

### ISSUE THREAD

**Issue by enygren** [tlswg/draft-ietf-tls-esni#135]
We may wish to have a way to indicate additional (extensible?) information relevant to establishing a connection alongside ESNIKeys in whatever record is introduced.  This increases the value of clients doing an additional DNS resolution in cases where it reduces future round-trips and reduces the need for subsequent DNS lookups.  In particular (and their might be others in the future):

* Being able to indicate that an Alternate Service (such as QUIC can/should be used).  Being able to switch directly to QUIC out of DNS without adding in additional resolutions, the need to go via TCP, or RTTs would add significant value and motivation to implement for clients and servers.

* Being able to indicate that HSTS should be used on a bareword hostname (ie, to default to HTTPS when no scheme is present).  This might unblock browsers from defaulting to HTTPS.

**Comment by ekr** [comment]
There already is such a field:

```
    struct {
        uint16 version;
        uint8 checksum[4];
        KeyShareEntry keys<4..2^16-1>;
        CipherSuite cipher_suites<2..2^16-2>;
        uint16 padded_length;
        uint64 not_before;
        uint64 not_after;
        Extension extensions<0..2^16-1>;   <---- HERE
    } ESNIKeys;````
