### ISSUE TITLE
Use ESNI in local discovery mode

### ISSUE THREAD

**Issue by huitema** [tlswg/draft-ietf-tls-esni#138]
I am looking at using ESNI for local private discovery. It would work as follow:

1) Authorized clients know the ESNI public key of the private server, which is otherwise kept secret.

2) Client initiates a DTLS session or a QUIC connection by broadcasting a message containing ESNI extension targeting the specific server.

3) Servers only respond if the recognize their key and name in the extension.

ESNI almost works as is for that, but not quite. First, the "record_digest" component allows identification and tracking of the server. In the private discovery mode, we would want to either not use it at all, or incorporate a nonce in the digest.

Second, ALPN. But you know that.

**Comment by martinthomson** [comment]
Re: ALPN: Why can't that be public?  You aren't intending to try to keep the fact that this is local private discovery, are you?

**Comment by huitema** [comment]
ALPN: It depends. Model 1 would be discovery over DTLS, i.e. handshake followed by DNS/MDNS over DTLS. Model 2 would be discovery integrated in the application, say using QUIC. The first client initial packet would be broadcast, and then the connection just proceeds.

**Comment by martinthomson** [comment]
I see, you are suggesting that - in model 2 - the connection is used for both discovery AND the application protocol.  I agree that the application protocol might be too revealing in that case.  "h3" might not be, but something more device-specific might leave nothing to the imagination.

**Comment by huitema** [comment]
Further analysis shows that even adding salt to the hash before computing the "record digest" will not help.  This is a defense in depth issue. The privacy of the discovery depends on keeping secret the "discovery ESNI key" of the service. If for some reason that key leaks, the attackers can mount active attacks and discover whether a target is present on a network. The record digest, even if it was salted, allows them to also perform passive attacks, such as looking at the digests in a log and checking whether they match a known key.

The simplest solution is to just omit the digest when using the ESNI extension for local discovery, e.g. when a DTLS or QUIC initial packet is received over a multicast address.

**Comment by kazuho** [comment]
> The simplest solution is to just omit the digest when using the ESNI extension for local discovery, e.g. when a DTLS or QUIC initial packet is received over a multicast address.

Sounds correct to me. To me it seems that the trade-off here is trial-decryption vs. exposing the key identifier. In the proposed local discovery scheme, every node is expected to perform trial decryption. That's fine for the proposed scheme, but not for ordinary ESNI keys in which we need a key identifier to avoid trial decryption.

**Comment by chris-wood** [comment]
This should be fixed by #166. @huitema, please reopen if that's not the case!
