### ISSUE TITLE
Minor nit: This is static DH, not DHE

### ISSUE THREAD

**Issue by jb-wisemo** [tlswg/draft-ietf-tls-esni#140]
Since the mechanism is essentially static DH key mode (with ephemeral client key), the text should not refer to it as DHE / ECDHE, as those acronyms indicate that both sides use a fresh ephemeral (EC)DH key for each connection, when the client-facing server is in fact using a fixed key (which may be rotated a lot more often than a key from a certificate).

**Comment by chris-wood** [comment]
We'll likely address this by adopting notation and terminology from HPKE. See #145.
