### ISSUE TITLE
Use the RFC1952/ISO3309/V.42 CRC32

### ISSUE THREAD

**Issue by jb-wisemo** [tlswg/draft-ietf-tls-esni#141]
Since the 32 bit checksum in ESNI records does not server a cryptographic purpose, only error detection, and since the chosen suite for the exchange does not necessarily use the SHA-256 algorithm, it would be more efficient to use a dedicated fast error detecting checksum.  The CRC32 algorithm used in RFC1952 (gzip), ISO 3309 and ITU-T V.42 is optimized for this task, widely available in software and hardware, and likely to already be implemented in ESNI using systems for other purposes.

This would also remove the only part of the draft that requires a specific single cryptographic algorithm, thereby making the specification algorithm agile without introducing any new algorithm registries for IANA to maintain.

**Comment by ekr** [comment]
I don't see how this makes it algorithm agile, it just requires baking in some other algorithm. Given that for the foreseeable future, every TLS 1.3 stack will have SHA-256, this would seem to make the implementation profile strictly worse. As for performance, the SHA-256 is trivial compared to the EC cost.

**Comment by jb-wisemo** [comment]
CRC32 makes no pretense to be a cryptographic algorithm, hence is not subject to the usual considerations of cryptographic algorithm agility.  A key lesson from baking SHA-1 into earlier protocols was that keeping it around for protocol compatibility made it more difficult to ensure it wasn't used in places where it would cause security issues.  Looking forward a few decades, there is little or no assurance that SHA-256 won't be in a similar situation.  In contrast the error detection abilities of CRC-32 (the only purpose it has in this place) has been proven mathematically, has survived for much much longer and is much faster to run before deciding if the cryptographic calculations are needed at all.  Like my other proposals, it's all about simplifying the protocol extension as much as possible.

**Comment by ekr** [comment]
I am familiar with these arguments, but I don't agree that this is a meaningful simplification. SHA-256 does not need to be agile in this case.

**Comment by DavidSchinazi** [comment]
I agree with @ekr here. Modern TLS implementations already have support for SHA-256 whereas CRC32 isn't always readily available.

**Comment by jb-wisemo** [comment]
You seem to misunderstand the issue.  The problematic scenario is this:

1. Many years from now, SHA-256 is broken by new research (not faster computers), similar to what happened to MD5.

2. Everyone works hard to remove SHA-256 from their cryptographic applications, or at least establish onerous review procedures to ensure any remaining SHA-256 invocation is not a security problem.

3. ESNI using SHA-256 for a non-cryptographic purpose will then become a very real practical liability, as every implementation will need to make excuses and audit documents just to prove they are not really using SHA-256 for anything risky.

If in contrast, ESNI used something non-cryptographic, like CRC-32 or the TCP checksum algorithm, this step 3 of the problem wouldn't happen.  Of the commonly implemented short checksums, CRC-32 is the only one optimized for detecting accidental data corruption, while the other are optimized for tiny speed margins at the cost of less effective detection.

As for CRC-32 being available in ESNI implementations, this is likely to be present already because it is used in gzip HTTP compression, but standard CRC-32 may be available for many other reasons.  Anyway, CRC-32 is a trivially small algorithm that doesn't need CPU specific optimization for the data sizes in question.

**Comment by ekr** [comment]
I understood the scenario and I've been through this before with SHA-1. I don't think that this is a particularly serious concern.

**Comment by chris-wood** [comment]
SHA-256 is fine for this purpose. Closing for now.
