### ISSUE TITLE
Eliminating record_digest

### ISSUE THREAD

**Issue by jb-wisemo** [tlswg/draft-ietf-tls-esni#142]
To simplify implementation, the record_digest can be eliminated as follows:

1. In ESNIKeys, provide a server-assigned 32 bit id.  Servers are free to manage that id space as they see fit e.g. to optimize lookup in a history of rotating keys.  However the server MAY obscure any structure in the numbering in any convenient manner.  As a further optimization, move all fixed length fields before the variable length fields and order them such that natural alignment is achieved (as per IETF tradition).

2. In ClientEncryptedSNI, insert the 32 bit id right after the Ciphersuite, making it part of the fixed-length part of the structure.  The record_digest field and its calculation is removed, thus reducing the size of the ESNI extension.

3. In ESNIContents, just use the full record instead of hashing it separately.  This costs a few extra blocks of hash invocations (as the cache record_digest can no longer be cached for each hash algorithm), but simplifies the code.  Alternatively, record_digest can be kept for this non-transmitted field to preserve that caching opportunity.

**Comment by chris-wood** [comment]
I'm not in favor of this proposal. Computing record_digest is quite trivial as is, and using SHA256 give us good assurance of its correctness. That is, we don't have to worry about servers possibly assigning incorrect IDs.

**Comment by martinthomson** [comment]
We do have to worry about collisions, which could be even harder to get right.  I don't think that sending it in the record makes any sense, but as an identifier, a hash is fine.

**Comment by martinthomson** [comment]
So my new insight here is that corruption of DNS records (if that does happen) will now be detected with `record_digest` and corrected through the use of the fallback mechanism.  So that makes `record_digest` important, but `checksum` useless.

**Comment by chris-wood** [comment]
Since a cryptographic proof of key possession is needed for downgrade protection, we can't remove record_digest in this way. Thus, I'm closing this issue as NTBF.
