### ISSUE TITLE
Adopt HPKE

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#145]
See https://datatracker.ietf.org/doc/draft-barnes-cfrg-hpke/ for more info.

**Comment by jb-wisemo** [comment]
Please don't.  The TLS series of RFCs and other related RFCs already contain established terminology for anything in the HPKE draft.   HPKE is basically two guys thinking they reinvented the wheel.

**Comment by ekr** [comment]
Hmm... As one of the designers of the construction in this current ESNI draft, I would welcome a more carefully vetted construction that came with the CFRG's endorsement.

**Comment by chris-wood** [comment]
I'd like to second what @ekr says. In a way, this document reinvents the wheel. We should defer such constructions to the CFRG.

**Comment by chris-wood** [comment]
This is part of #207, as discussed in Singapore.

**Comment by chris-wood** [comment]
Fixed by #207.
