### ISSUE TITLE
Require OCSP stapling for ESNI

### ISSUE THREAD

**Issue by J0WI** [tlswg/draft-ietf-tls-esni#156]
Since OCSP is [leaking](https://bugzilla.mozilla.org/show_bug.cgi?id=1535235#c3) the server name, ESNI should probably enforce OCSP stapling (similar to [RFC 7633](https://tools.ietf.org/html/rfc7633)) or any other way of encrypted OCSP checks.
Ignoring OCSP status checks entirely makes it hard to revoke a certificate, even if it's only valid for a few months.

**Comment by chris-wood** [comment]
@J0WI what behavior do you expect here? Would clients fail hard if server don't send stapled responses? It's good to view ESNI as part of the leaky boat problem. It plugs one hole, but not all of them. Implementations probably should do something about cleartext OCSP if they want all holes plugged.
