### ISSUE TITLE
Lingering references to `sni` instead of `dns_name`

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#173]
From Stephen Farrell on the TLS WG list:

Just spotted that:

   opaque zeros[ESNIKeys.padded_length - length(sni)];

should I guess now be:

   opaque zeros[ESNIKeys.padded_length - length(dns_name)];

And maybe s/PaddedServerNameList/PaddedDNSName/ would also make sense.

**Comment by ghedo** [comment]
Think this is fixed now?
