### ISSUE TITLE
Decouple ESNIKeys and the envelope DNS record

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#179]
This will let us adopt another delivery mechanism (HTTPSVC?) if needed later on.

**Comment by ghedo** [comment]
We already have `ESNIKeys` and `ESNIRecord` as different structures, wouldn't a different delivery mechanism be able to simply wrap `ESNIKeys` in its own transport, without the DNS record? I guess this point could be clarified though.

**Comment by chris-wood** [comment]
This is mostly an editorial change to make it easy to remove `ESNIRecord`, if needed, without changing any other text.

**Comment by chris-wood** [comment]
Fixed by #187.
