### ISSUE TITLE
Consider disabling server tickets if tickets are not uniform across the ESNI anonymity set

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#182]
Tickets and ESNI interact in a weird way, i.e., they may leak size or contain the SNI, leading to potential issues. One might want to disable them if also offering ESNI as a service.

**Comment by davidben** [comment]
Just to confirm, by uniform do you just mean that they're indistinguishable visually or that the server will cross-resume across names in the anonymity set?

**Comment by chris-wood** [comment]
Both!

**Comment by davidben** [comment]
I'm not sure we want the latter. For instance, if they have different client certificate requirements, the server could be in a pickle resuming across them allows you to bypass those requirements. It also generally muddles the identity that the server is authenticating as. In the split mode case, the different backends presumably don't even share ticket keys.

Is the motivation is various attacks around seeing if the server accepts a ticket in various contexts? That would certainly solve this, but I wonder if we can address them by playing games with binders instead? Though it's a little fussy since binder failures are fatal, whereas failing to decrypt a ticket just falls back to full handshake...

**Comment by chris-wood** [comment]
> For instance, if they have different client certificate requirements, the server could be in a pickle resuming across them allows you to bypass those requirements.

Correct! The issue as written isn't crisp :-) What we require, among possibly other things that I didn't write down, is that the information and authentication context for a ticket is indistinguishable across all tickets possible for a given set of servers. So in the example you describe, if a client gets a ticket without authenticating from one server and then resumes it to a different server that normally would require authentication, then the ticket must record whether authentication took place. And storing that bit should not reveal information about the name.

(I was just aiming to make a note of this so I didn't forget it later. There's probably other things to consider, too. I don't claim this is complete as written!)

> Is the motivation is various attacks around seeing if the server accepts a ticket in various contexts? 

Yep! This is a "flip table" solution to the problem that some server operators may wish to do.

**Comment by huitema** [comment]
@chris-wood Is this about privacy or about authentication? It seems that we have two issues:

1) Observers perform some trials and find out that "hidden1.example.com" uses 33 bytes tickets while "hidden2.example.com" uses 42 bytes. They can then look at TLS resume attempts and tell which server is contacted. 

2) Attackers find out that some servers send a ticket after authentication and other before that, and then use clever repeat attacks to benefit from the confusion.

I would argue that (1) is part of the wider issue of identifying servers without breaking the encryption. We may want to address it, but it seems very complicated.

As for (2), is this an ESNI issue or a TLS issue?

**Comment by chris-wood** [comment]
@huitema it's about privacy. As you observe, (1) is clearly an issue for ESNI, but it's more an attack on tickets than it is on ESNI. It seems that if ESNI is to provide desired guarantees, then we ought to address it. (2) is a TLS issue and not related to ESNI. (Servers shouldn't be minting tickets without also including the authentication context. I'd rather not go down that rabbit hole here. :-))

**Comment by huitema** [comment]
(1) is a matter of degree. It is also possible to fingerprint servers by looking the sizes of pages, or the sizes of TLS blocks, or the profile of a typical session. There was a talk about that in one of the ANRW presentations.

Let's assume that we want to standardize ticket sizes. Suppose that a fronting server says "to hide behind me you should pad your tickets to exactly 64 bytes". We are then going into two kinds of arguments. 

First, many sites owner will ask you "how exactly do I do that with Apache2?" So if you want uniformity, you need some deployment guidelines, and you want support in the main server distributions. Or the TLS stacks. Or the QUIC stacks. But then we are getting a bit beyond the scope of ESNI.

Second, there will be the occasional site that has the requirement for 67 bytes. Or 129. What do you do? Increase the size for everybody else? Suggest plausible sizes? Randomize?

**Comment by chris-wood** [comment]
> It is also possible to fingerprint servers by looking the sizes of pages, or the sizes of TLS blocks, or the profile of a typical session. There was a talk about that in one of the ANRW presentations.

Indeed! However, the attack in mind is arguably much simpler than fingerprinting, so I'm not sure we should lump them in the same bucket. 

On the question of sizes, note that we already recommend padding to hide certificate sizes. Making a similar suggestion for tickets therefore seems reasonable to me.

**Comment by kazuho** [comment]
Yeah, I now realize that the advice on certificate size seems a bit odd, as the size is not something that is exposed on the wire. To be accurate, I think what we care is the number of TLS records and their sizes transmitted during the handshake. Those are the things that are exposed on the wire.

Similarly, the contents of Client Hello and Server Hello are also exposed.

Considering that, it might be a good idea to recommend as a general rule to not expose _plaintext_ information that helps observers reduce the anonymity set, using the tickets and the size of the certificate as the examples.

**Comment by chris-wood** [comment]
> Considering that, it might be a good idea to recommend as a general rule to not expose plaintext information that helps observers reduce the anonymity set, using the tickets and the size of the certificate as the examples.

Yes, that would certainly be an improvement! Would you mind preparing a PR to that effect? I can do it if you don't have the time.

**Comment by kazuho** [comment]
@chris-wood I'd appreciate it if you could, as I'm not sure when I can do it.

**Comment by chris-wood** [comment]
Closing as this is effectively included in #209!
