### ISSUE TITLE
Clarification on repeated extensions in ESNIRecord and ESNIKeys

### ISSUE THREAD

**Issue by dmcardle** [tlswg/draft-ietf-tls-esni#183]
[RFC8446 section 4.2](https://tools.ietf.org/html/rfc8446#section-4.2) states:

> There MUST NOT be more than one extension of the
   same type in a given extension block.

The ESNI draft should probably explicitly restate this for both `ESNIRecord.dns_extensions` and `ESNIKeys.extensions`.  I'd be happy to make a PR if need be. Thanks!

**Comment by chris-wood** [comment]
@dmcardle if you could propose text that takes the new ESNIConfig and HTTPSSVC change into account, that'd be great!

**Comment by chris-wood** [comment]
Fixed by #195.
