### ISSUE TITLE
Why is the PaddedSNI padded with zeros?

### ISSUE THREAD

**Issue by sayrer** [tlswg/draft-ietf-tls-esni#191]
Couldn't these extra bytes be any value?

**Comment by chris-wood** [comment]
Yes, but zeroes are quite common. See, e.g., TLS 1.3 record-layer padding: https://tools.ietf.org/html/rfc8446#section-5.4.

**Comment by sayrer** [comment]
Would you mind reopening this issue? I think a MUST requirement with a rationale of "everyone else does it" seems wrong.

I can think of some reasons to mandate zeros:

- prevent ad-hoc extensions
- prevent clients from intentionally weakening traffic

stuff like that. I just think the draft should state the rationale.

**Comment by ekr** [comment]
I would prefer that we not add any rationale. This is a reasonable choice and if we add a rationale for everything that is reasonable the draft will get quite long.

Second, we are actively considering a number of PRs here, at least one of which does not even have these bytes, so effort spent justifying them is potentially wasted.

**Comment by sayrer** [comment]
> I would prefer that we not add any rationale. This is a reasonable choice and if we add a rationale for everything that is reasonable the draft will get quite long.

It's a not a reasonable choice if there is no reason for it.

> Second, we are actively considering a number of PRs here, at least one of which does not even have these bytes, so effort spent justifying them is potentially wasted.

That makes sense. What's the link?

**Comment by ekr** [comment]
It's a not a reasonable choice if there is no reason for it.

**Comment by chris-wood** [comment]
@sayrer I don't think this needs rationale. Padding with zeros is more or less convention in TLS, and we've stuck with it.

**Comment by sayrer** [comment]
> It's a not a reasonable choice if there is no reason for it.

Jokes aside, what would the rationale be for this requirement?

"The SNI must be padded with zeros, because ________".

It may be the case that other TLS specs have used zeros.

**Comment by ekr** [comment]
I'm not sure why you think that every design decision in the specification needs to have a rationale in the specification. That's not any kind of IETF requirement.

If you have some objection to this design choice, I suggest you raise it on the mailing list and see if others agree.

**Comment by sayrer** [comment]
It's true that not every requirement needs a rationale. Some of them are obviously in service of the goals of the draft itself: for example, no one is claiming that the document should justify encryption. It's also reasonable to cite other documents as the way to do things: there's no need to provide a rationale for the use of AEAD, for instance.

But, the choice of server-controlled zeros for this padding is specific to this draft. It seems like this requirement would be better as a server-specified minimum length, where the field is variable length and filled with opaque data (zeros are acceptable).

**Comment by martinthomson** [comment]
We've been bitten by requirements for opaque data in the past.  See POODLE.

**Comment by sayrer** [comment]
> We've been bitten by requirements for opaque data in the past. See POODLE.

This comment seems ambiguous enough to warrant reopening the issue.
