### ISSUE TITLE
How to parse esni_retry_request generically?

### ISSUE THREAD

**Issue by ocheron** [tlswg/draft-ietf-tls-esni#192]
As of draft-ietf-tls-esni-04, when the server rejects ESNI with esni_retry_request, it includes one or more ESNIKeys for retry:
```
      struct {
          ServerESNIResponseType response_type;
          select (response_type) {
              case esni_accept:        uint8 nonce[16];
              case esni_retry_request: ESNIKeys retry_keys<1..2^16-1>;
          }
      } ServerEncryptedSNI;

   retry_keys  One or more ESNIKeys structures containing the keys that
      the client should use on subsequent connections to encrypt the
      ClientESNIInner structure.
```

The client behavior described in section 5.1.2 is to pick one of the ESNIKeys values from this vector:

> If one of the values contains a version supported by the client,
> it can regard the ESNI keys as securely replaced by the server.
> It SHOULD retry the handshake with a new transport connection,
> using that value to encrypt the SNI.

Encoding of `retry_keys` contains the total size of the vector field but not the size of the individual ESNIKeys elements. This makes it difficult (impossible?) to parse a vector with unknown future versions, so this part is not really extensible.

**Comment by davidben** [comment]
Thanks for the comment! https://github.com/tlswg/draft-ietf-tls-esni/pull/198 should resolve this. It's a little goofy-looking but ah well.

**Comment by ocheron** [comment]
Thank you for confirming the issue. Not the nicest but will be effective.
It's the only real blocking point I see when implementing draft -04.
