### ISSUE TITLE
Anonymity sets

### ISSUE THREAD

**Issue by sayrer** [tlswg/draft-ietf-tls-esni#204]
Even if #146 and #139 are closed without further edits, I think the draft should clarify the intended anonymity set for ESNIConfig and its associated record_digest. The draft does address this in section 7.5.2. "Avoid widely-deployed shared secrets", but I missed that. Additionally, the draft uses the term "anonymity set" only once, in section 6.1. "Misconfiguration and Deployment Concerns".

The explanation Ben Schwartz wrote on the list is very clear:

"The record_digest, like the ESNIConfig itself, is intended to be constant across all domains that form an anonymity set (i.e. O(1) ESNIConfigs per CDN).  Thus, the record_digest reveals no additional information to an onlooker who can observe the server IP."

Perhaps a short section on anonymity sets would clarify this. I think some combination of section 7.5.2 and the last paragraph of the introduction would work.

**Comment by chris-wood** [comment]
@sayrer text to clarify this would be most welcome. Please provide a PR!

**Comment by ret394** [comment]
is the clarification still required? just curious.

**Comment by chris-wood** [comment]
Indeed, I'm not sure further clarification is needed. Given no action on this issue, I'm closing. Please propose a PR or text if you feel this still needs to be fixed!
