### ISSUE TITLE
Bikeshed: finalize on naming of "ECHO"

### ISSUE THREAD

**Issue by enygren** [tlswg/draft-ietf-tls-esni#232]
While cutsy, the name "ECHO" for "Encrypted Client Hello" seems like it could cause problems and significant confusion.  To those not actively involved in the working group, "ECHO" has very different connotations.  Some potential risks include:
* Other IETF standards have some form of "ECHO" functionality.  When bouncing this question off someone else, they responded with "TLS ECHO, like ICMP ECHO, except totally not"
* The immediate guess people may have on hearing about a TLS ECHO functionality would be to think "oh, like to echo back a message for heartbeat purposes?".  Given the potential risk for confusion with heartbeat (especially given "Heartbleed") this has some risk of giving TLS ECHO a bad rap from the start due to confusion.
* This functionality is going to have high profile with product managers and perhaps even government regulators and public policy.  Applying a name that has confusing lay-connotations is going to muddle conversations.
* This has a risk of confusion when used in other contexts.  For example, "echoconfig" as a SVCB parameter key has potential risk for confusing people reading the config and lacking context.
* ECHO is going to be harder to do searches for, both in Internet and intranet search engines.

Just calling it "ECH" or "EHELLO" may be safer?

(If this changes, SVCB will also need to change the "echoconfig".)

**Comment by enygren** [comment]
One reason for "EHELLO" is that if we support Split Mode with the ClientHelloInner being TLS 1.2 then it also provides protection for the ServerHello as well.

**Comment by martinthomson** [comment]
ETCH

**Comment by enygren** [comment]
ETCH == "Encrypted TLS Client Hello"?    (That also sounds like a fine option.)
