### ISSUE TITLE
Consider strict ECH mode

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#240]
From a TODO in the draft:

Key replacement is significantly less scary than saying that ECH-naive servers bounce ECH off. Is it worth defining a strict mode toggle in the ECH keys, for a deployment to indicate it is ready for that?

cc @davidben

**Comment by davidben** [comment]
I imagine clients that talk to general HTTPS servers like browsers wouldn't do this, but maybe more dedicated clients would? I work on a browser and don't know much about those kinds of use cases, so I figured I'd leave it as a TODO in case the WG felt strongly one way or another.

**Comment by chris-wood** [comment]
Given that no one asked for this, I'm inclined to close this without action. So... doing that now. :)
