### ISSUE TITLE
Describe risks and mitigations for privacy leaks from configuration digest

### ISSUE THREAD

**Issue by sharpie7** [tlswg/draft-ietf-tls-esni#245]
The ID proposes an optional configuration digest parameter to be included in the clientHello. This parameter is advantageous because it improves the efficiency of the solution by avoiding the server having to do trial decryptions. However, in some scenarios the configuration digest could leak privacy information. In version 7 of the ID, section 10.2 on “Client Tracking” describes one scenario, but there are others. A more complete and general discussion of the risks and mitigations would be useful.

If a particular domain has a unique public key then the configuration digest becomes a fingerprint for that domain. An attacker that has a list of such domains that they want to monitor can build a dictionary of the corresponding digests use this to identify traffic to the domains on their list.

Some mitigations could be:
1)	Avoid the use of configuration digest
2)	Only deploy in a mode where many domains share the same public key to make finger-printing too general to be useful
3)	To change keys faster than attackers can update their list of fingerprints

**Comment by chris-wood** [comment]
This should be addressed by #247. Please re-open (and suggest text edits!) if you think otherwise.
