### ISSUE TITLE
Decryption failure guidance could be more detailed for trial decryption

### ISSUE THREAD

**Issue by raycoll** [tlswg/draft-ietf-tls-esni#248]
Hello,

In section 8, there is a description of two approaches to match an ECHConfig with the ClientEncryptedCH:

```
This matching procedure should be done using one of the following two checks:
1. Compare ClientEncryptedCH.record_digest against cryptographic hashes of known ECHConfig and choose the one that matches.
2. Use trial decryption of ClientEncryptedCH.encrypted_ch with known ECHConfig and choose the one that succeeds.
```

And later, we have guidance on what the server should do if decryption fails:

```
If decryption fails, the server MUST abort the connection with a "decrypt_error" alert.
```

This guidance makes sense to me for a server that is using record_digest matching to select an ECHConfig. If decryption fails using the matching record_digest, we must abort. However, I think it could be more clear for the trial decryption case, which is expected to have failed decryption attempt(s). 

I think something like this could be more clear:

```
If record_digest matching is used and decryption fails using the matching ECHConfig, the server MUST abort the connection with a "decrypt_error" alert.
```

**Comment by chris-wood** [comment]
I think this is clarified above in that section. Namely, for trial decryption, we say that the record_digest does not "match" the ClientHello if there's no key which successfully decrypts the ClientHello. In this case, the server ignores the ECH extension and proceeds as specified. A "match" in the trial decryption case therefore implies that a key successfully decrypts the ClientHello, so the text referenced ("If decryption fails...") does not apply.

@raycoll, does that clarify?

**Comment by ekr** [comment]
I also feel like this is clear.

**Comment by raycoll** [comment]
On reread, that makes sense. Thanks!
