### ISSUE TITLE
Common supported KEM

### ISSUE THREAD

**Issue by FredericJacobs** [tlswg/draft-ietf-tls-esni#251]
It might make sense to have a default KEM that all implementations would need to support for each ECH version.

This would prevent clients to have to support all KEMs at the risk of falling back to plaintext because they don't support the server-supported KEM.

**Comment by ekr** [comment]
As Chris Patton says, we should also specify an AEAD and KDF. These should be AES-GCM and HMAC-SHA256.

**Comment by chris-wood** [comment]
From the interim: HPKE(x25519, AES-128-GCM, SHA-256)
