### ISSUE TITLE
Nonce rationale clarity

### ISSUE THREAD

**Issue by bemasc** [tlswg/draft-ietf-tls-esni#253]
There are several rationales provided about the need for `ech_nonce`:

1. This nonce ensures that the server's encrypted Certificate can only be read by the entity which sent this ClientHello.
2. Since servers process either ClientHelloInner or ClientHelloOuter, and ClientHelloInner contains an HPKE-derived nonce, it is not possible for an attacker to "cut and paste" the ECH value in a different Client Hello and learn information from ClientHelloInner. This is because the attacker lacks access to the HPKE-derived nonce used to derive the handshake secrets.
3. Client Reaction Attack Mitigation ... The "ech_nonce" extension in the inner ClientHello prevents this attack. In particular, since the attacker does not have access to this value, it cannot produce the right transcript and handshake keys needed for encrypting the Certificate message. Thus, the client will fail to decrypt the Certificate and abort the connection.

These rationales are all subtly different, and having read them all, I still don't understand why the nonce is necessary, when the server_handshake_traffic_secret already depends on the inner client random, which is not known to the attacker.

I would appreciate some more explanation on this point.  It also might make sense to move these rationales up into the ech_nonce section, or add forward references to them there.

**Comment by cjpatton** [comment]
I agree that the rationale isn't clear from the description. This needs to be cleaned up. However, it does seem to prevent a real attack (see Sec. 10.8.1).

**Comment by bemasc** [comment]
@cjpatton As I noted above, the server_handshake_traffic_secret already depends on the inner client random, which is not known to the attacker.  It therefore seems to me that the attacker therefore cannot produce a Certificate message that the client will decrypt, even without the nonce.  If that's true, I don't see how the attack in Sec. 10.8.1 is possible.

**Comment by cjpatton** [comment]
What if the inner CH.random is the same as the outer CH.random? This is currently allowed by the spec, i.e., there's no guidance on "copying" extensions from the outer CH to the inner.

**Comment by bemasc** [comment]
That's an interesting question that I think the spec should probably address.  I assumed they could not be the same, because they are both required to be random.  If they _can_ be the same, I would suggest making them always the same, and remove the inner one to save 32 bytes and simplify the analysis.

**Comment by cjpatton** [comment]
The semantics of copying outer CH extensions into inner CH needs to be clarified: see also https://github.com/tlswg/draft-ietf-tls-esni/issues/262. To my read, the intent is that any extension MAY be copied, bit-by-bit, into the inner CH.

**Comment by bemasc** [comment]
The client random is a fixed field of the ClientHello, not an extension.

**Comment by chris-wood** [comment]
> If they can be the same, I would suggest making them always the same, and remove the inner one to save 32 bytes and simplify the analysis.

Hmm, I'm not really a fan of this (and bit shaving in general). The idea is to make the inner CH as close to a full CH as possible, so keeping the same encoding makes most sense to me. 

That said, even if they are random, there may be cases where the attacker can predict the randomness generated.

**Comment by davidben** [comment]
I think an attacker that can predict a random value generated by the TLS stack has much more exciting avenues of attack here. (E.g. the client's key share is lost.) Though it is a good point that they are slightly different: the ECH nonce is exported from the HPKE context while the client random is simply random. I forget if that ends up being important anywhere.

**Comment by cjpatton** [comment]
> The client random is a fixed field of the ClientHello, not an extension.
Ah you're right. Thanks!

**Comment by chris-wood** [comment]
Exactly -- even if an attacker knew the client's key share, random value, etc, it *might* not know the ECH nonce (without access to the sever's private key), depending on the KEM used. (If DHKEM was used, it would know the client's ephemeral private key, so the point is moot.) 

All that said, we *may* be able to remove it. But I'm hesitant to do so without backing analysis.

**Comment by davidben** [comment]
> If DHKEM was used, it would know the client's ephemeral private key, so the point is moot.

I think this is true for any KEM. If your KEM looks more like public key encryption, the attacker would instead know the shared secret the client generated. More generally, if we assume the client is incapable of generating random numbers, the attacker can simply run through the client's implementation of SetupBaseS, replacing all non-determinism with the predicted random number. It will then end up with the same HPKE context.

**Comment by chris-wood** [comment]
> I think this is true for any KEM. If your KEM looks more like public key encryption, the attacker would instead know the shared secret the client generated. More generally, if we assume the client is incapable of generating random numbers, the attacker can simply run through the client's implementation of SetupBaseS, replacing all non-determinism with the predicted random number. It will then end up with the same HPKE context.

That's true!

**Comment by bemasc** [comment]
RFC 8446 Appendix C.1 says "Implementations can provide extra security against [broken RNG] attack by using separate CSPRNGs to generate public and private values.".  If that's the motivation for the nonce, I think the spec should mention it.

**Comment by cjpatton** [comment]
This is the current proposal for removing "ech_nonce" and clarifying behavior around choosing the ClientHelloInner.random: https://github.com/tlswg/draft-ietf-tls-esni/pull/292

**Comment by chris-wood** [comment]
Closing now that #292 landed.
