### ISSUE TITLE
Need a high-level description of the security goal in the intro

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#260]
In just a few sentences, let's define the anonymity set and say what it means for connections to end points in this set to be indistignuishable. We might also enumerate non-goals (though we still need consensus on what these are).

**Comment by chris-wood** [comment]
Attackers:
- Passive attackers are those which cannot probe, e.g., buggy middleboxes that filter based on plaintext packet contents.
- Active attackers can probe, e.g., censors. 

Goals:
- ECH does not negatively affect any existing security properties of TLS 1.3.
- ECH connections to servers in the same anonymity set are indistinguishable from one another, modulo traffic analysis. (Note: an anonymity set is determined by the client and server parameters, e.g., the SNI, supported application protocols, and so on.)
- ECH support is secret from passive attackers who don't know the ECH configuration, but not active attackers. 
- ECH usage is secret from passive attackers who don't know the ECH configuration, but not active attackers. More specifically:
  - Passive attackers with a known ECH configuration can distinguish between a connection that negotiates ECH with that configuration and one which does not (GREASEd or using a different configuration).
  - Passive attackers without the ECH configuration cannot distinguish between a connection that negotiates ECH and one which does not (but GREASEd).
  - Active attackers can distinguish between a connection that negotiates ECH and one which does not (but GREASEd).

**Comment by ekr** [comment]
Yeah this looks good.

**Comment by chris-wood** [comment]
From the interim: merge this as a PR and then address censorship separately (if desired).
