### ISSUE TITLE
"outer_extensions" mechanism is lossy compression

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#262]
Say we want the outer CH to have extensions a and b. Let's write this as
```
  ClientHelloOuter = [a, b]
```
Say the inner CH should have extensions a, b, c, and d. But b is really big, so we want a shallow copy it. Then we write the compressed inner CH as
```
   ClientHelloInner = [a, c, d, outer_extensions = [ shallow_copy_of_b ]]
```
The decompressed ClientHelloInner should be `[a, b, c, d]`, but using `outer_extensions` destroys the intended order.

**Comment by davidben** [comment]
Extension order in TLS isn't meaningful, so I think that's fine, provided the code producing the inner ClientHello and the code encoding it get to coordinate. (I.e. a client that says "I don't care about secrecy of `key_share` and will send the same one on both sides" can probably live with `key_share` being at the end.)

There have been cases where extension order has interop impacts due to server bugs. (E.g. the last extension needs to be non-empty to avoid a bug in some old servers.) But those old servers wouldn't see inner ClientHellos anyway.

**Comment by chris-wood** [comment]
I think maybe a concern is that the client and server wind up using extension lists with different orders, for whatever reasons, thereby yielding different transcripts. Wouldn't that be an issue?

**Comment by davidben** [comment]
Right, hence "provided the code producing the inner ClientHello and the code encoding it get to coordinate". If compression is done with inner + outer ClientHello being produced by the same thing, the client can simply take this into account and always put referenced extensions at the end. If it's a proxying picture, where the client does not know it is doing ECH (does that work? I suspect the ech_nonce would be an issue), that may not work.

**Comment by chris-wood** [comment]
Right. I don't expect the latter (proxy case) to be common, though perhaps modifying this to prevent misuse might be useful.

**Comment by cjpatton** [comment]
This make me worry about interoperability. For a client and server to speak to eachother they need to adopt the same convention that is not specified anywhere.

**Comment by davidben** [comment]
It is certainly necessary that the decompression function produces a deterministic ClientHello, down to what goes into the transcript. I think section 6.1 does that. That's a different criteria from requiring that every possible input ClientHello be efficiently compressible.

**Comment by cjpatton** [comment]
I don't compare about it being "efficiently" compressible, but I see your point about the transcript being the same. Just to clarify, my concern is in Section 6.1: 

> Then,
   the client removes and and replaces extensions from ClientHelloInner
   with a single "outer_extensions" extension.  The list of
   outer_extensions include those which were removed from
   ClientHelloInner, in the order in which they were removed.

I interpret this as the following procedure:
```python
   outer_extensions = OuterExtensions()
   for extension in client_hello_inner.extensions:
      if extension in client_hello_outer and too_big(extension.get_payload()):
          outer_extensions.append(extension.get_type())
      extension.remove() # Removes extension from client_hello_inner
   client_hello_inner.extensions.append(outer_extensions)
```
is it clear what i mean here? Do we agree that, in general, this procedure doesn't preserve the order of extensions?

My concern had to do with servers being ossified around the order of extensions. If this isn't a problem, then I guess we're good here. It's worth flagging this, however (from RFC 8446): 

>    When multiple extensions of different types are present, the
   extensions MAY appear in any order, with the exception of
   "pre_shared_key" (Section 4.2.11) which MUST be the last extension in
   the ClientHello (but can appear anywhere in the ServerHello
   extensions block).  There MUST NOT be more than one extension of the
   same type in a given extension block.

**Comment by davidben** [comment]
The alternative doesn't quite work because extensions can legitimately be empty, so it's ambiguous whether you meant to explicitly encode an empty extension or reference the outer one. For example, the old TLS 1.2 `session_ticket` extension was empty to signal "I support tickets but am not sending one" and a non-empty string to send a ticket.

That's a good point though. The compression algorithm in 6.1 breaks if the removed extensions are non-contiguous, so it should either include that requirement, or we come up with a different goofy encoding. :-)

**Comment by cjpatton** [comment]
Ah, good point. I would be fine with adding the requirement, though it might be worth trying to come up with something more general.

**Comment by davidben** [comment]
One possible replacement paragraph:

> When sending ClientHello, the client MAY substitute extensions which it knows will be duplicated in ClientHelloOuter. To do so, the client arranges the duplicate extensions contiguously in the extension list when computing ClientHelloInner, including any PSK binders. The client then computes a hash of the entire ClientHelloInner message with the same hash as for the KDF used to encrypt ClientHelloInner. Finally, the client removes and replaces extensions from ClientHelloInner with a single "outer_extensions" extension. The list of outer_extensions include those which were removed from ClientHelloInner, in the order in which they were removed. The hash contains the full ClientHelloInner hash computed above.

(I'm also fine with replacing with a more general encoding.)

**Comment by cjpatton** [comment]
We should also require that the "outer_extensions" extension appears where the contiguous extensions were. For example,  to compress `b` and `c`, we encode `[a, b, c, d]` as `[a, outer_extensions = [b_shallow_copy, c_shallow_copy], d]`.

**Comment by cjpatton** [comment]
In fact, that leads to a more general encoding I think.

**Comment by cjpatton** [comment]
The proposed change is here: #293.

As @ekr suggested in the interim meeting, before changing this mechanism, we should look at real ClientHellos to see what we would actually want to compress.

**Comment by davidben** [comment]
My inclination is also that the contiguous constraint is probably fine, though we have played games with extension ordering before with the PSK extension. Although I would actually anticipate compressing most extensions, and just ordering things to match. Most of them aren't sensitive and, assuming you're already compressing one extension, even an empty extension would cost just four bytes uncompressed and two bytes compressed.

**Comment by cjpatton** [comment]
I'm pretty happy with the state of things. I'm closing this issue.
