### ISSUE TITLE
"outer_extensions": What's the purpose of the hash?

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#263]
Field `OuterExtensions.hash` is computed as "digest of the complete ClientHelloInner" (including presumably, the "outer_extensions" extension). I don't understand the analytical value of this hash. Can anyone explain its reasoning?

**Comment by ekr** [comment]
The hash is intended to prevent the attacker from influencing the reconstructed CHInner by manipulating CHOuter. Consider the contrived example of an extension which is separately protected but only works for SNI-A and not SNI-B. E.g., it's constructed by doing E(K_sni, SNI). If that extension were included in CHOuter and then imported into CHInner via this mechanism, then an attacker could substitute it and use a reaction attack to determine whether the CH referred to A or B.

However, with the hash (which may be not well-specified), this attack gets caught by the client-facing server and the handshake is rejected without leaking information.

**Comment by cjpatton** [comment]
My initial understanding of this mechanism was incorrect. What happens is that the hash is computed over the ClientHelloInner that is consumed by the backend server. This is intended to ensure that if ECH accepts, then the backend server consumes the CH intended by the client. (PR https://github.com/tlswg/draft-ietf-tls-esni/pull/293 makes this more clear, I think.)

I wonder if this mechanism is redundant. Agreement on the CH between the client and backend server is provided by the binding of the transcript hash to the handshake traffic secret, so any attempt to manipulate the ClientHelloInner by fiddling with the ClientHelloOuter should be detected. On the other hand, the binding of the outer extensions to ClientHelloInner ensures agreement on the CH *prior to the backend server consuming it*. This is a strictly stronger property, which may or may not be useful.

> Consider the contrived example of an extension which is separately protected but only works for SNI-A and not SNI-B.

I agree that the attack works, but the example seems *really* contrived :) I'd be interested if there are more natural extensions for which this extra layer of security would be useful.

**Comment by cjpatton** [comment]
From the interim meeting, the consensus seems to be that we should err on the conservative side.

**Comment by cjpatton** [comment]
Let's close this issue and leave the mechanism as is.

**Comment by cjpatton** [comment]
Hrm, before closing I think it might be worth noting, in the spec, the stronger security property this provides.

**Comment by bemasc** [comment]
I think we should also consider binding the CHInner to a hash of the whole CHOuter (minus the ClientEncryptedCH extension).  That would have the same size overhead, but would give us a stronger property: modifying anything in CHOuter (not just one of the copied extensions) invalidates the whole thing.

**Comment by cjpatton** [comment]
The point of hashing outer extensions is to provide integrity of the ClientHelloInner. What would be the point in hashing more of the ClientHelloOuter? (Not a rhetorical question :) It seems conceptually different, and I'm curious what the security benefit might be.)

**Comment by davidben** [comment]
If we authenticate the ClientHelloOuter, we'd be authenticating all the inputs that go into the ClientHelloInner, so I think that would also provide integrity. I expect Ben is suggesting this in the context of https://github.com/tlswg/draft-ietf-tls-esni/pull/287#issuecomment-686746358, where GREASE can additionally be made a little stronger if we did that. Getting that to interact well with any PSK binders in ClientHelloOuter is tricky though, unless we decide to ban resumption attempts in outer ClientHellos.

(Probably best to keep the GREASE-related conversation in one place. Though I see I didn't help on that front because some discussion is also in #274. Ah, GitHub.)

**Comment by bemasc** [comment]
Yep, I'm just echoing @davidben's observation. See also https://github.com/tlswg/draft-ietf-tls-esni/issues/274#issuecomment-686768299.

**Comment by cjpatton** [comment]
> If we authenticate the ClientHelloOuter, we'd be authenticating all the inputs that go into the ClientHelloInner, so I think that would also provide integrity.

Today, the only thing that gets copied into ClientHelloInner is extensions, so I don't see how it's an improvement in terms of our primary security goal. (Not sure about the "don't stick out" benefit.)

**Comment by ekr** [comment]
I don't understand how hashing all of CHOuter is going to work. In split
mode, the server never sees any of CHOuter.

**Comment by bemasc** [comment]
Yes, the hash would be checked when reconstructing the inner ClientHello (as here), and would not be present in the reconstructed ClientHello.

**Comment by cjpatton** [comment]
There's not much discussion here. Unless there's objection, shall we leave the mechanism as-is and close out this issue? cc/ @chris-wood

**Comment by bemasc** [comment]
Works for me.
