### ISSUE TITLE
Handshake-level vs record-level padding

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#264]
ECH currently uses two different kinds of padding. The encrypted ClientHello is padded with the padding extension, while the server response is padded with TLS 1.3 record layer padding.
https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-07#section-7.1
https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-07#section-7.2

Using record-level padding in TLS over TCP is relatively straightforward as it’s ordered. However DTLS and QUIC have their own record layers, with retransmission logic. Properly hiding some length then requires that packet loss and retransmission logic track and retransmit padding as if it were integrated into the byte stream.

In the case of QUIC, when a QUIC packet is determined to be lost, it is not retransmitted whole; instead information carried in the frames in lost packets might be sent again in new frames (draft-ietf-quic-transport, section 13.3). That same section states that PADDING frames do not need to be retransmitted. If ECH in QUIC relies on QUIC transport layer padding, that would need to be changed, and implementations would need to track how much adding is associated with CRYPTO frame data for retransmission.

QUIC additionally needs the padding size communicated across API boundaries between the TLS and QUIC implementations. It’s likely that everyone’s first pass at the API will omit this, only to need to add an extra parameter (API change) later when they implement ECH.

This seems a somewhat general issue between padding at reliably- and unreliably-transmitted layers of the stack. HTTP/3 has something analogous (though carried in slightly frames). That draft actually discusses two options for padding and calls out the relation to packet loss:

> Where HTTP/2 employs PADDING frames and Padding fields in other frames to make a connection more resistant to traffic analysis, HTTP/3 can either rely on transport-layer padding or employ the reserved frame and stream types discussed in Section 7.2.8 and Section 6.2.3. These methods of padding produce different results in terms of the granularity of padding, how padding is arranged in relation to the information that is being protected, whether padding is applied in the case of packet loss, and how an implementation might control padding. Redundant padding could even be counterproductive.

https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-padding-and-traffic-analysi

Should we match that precedent and move the padding into the handshake itself? That would make it apply to DTLS and QUIC transparently. If we do, a couple possibilities to start with:

* Say that ECH implementations must tolerate unsolicited padding extensions and inject those into various messages. This is a goofy around messages without extensions (CertificateVerify), or messages with multiple extension blocks (Certificate), but as long as there is an extension block _somewhere_ in each padded flight, it's probably possible to fudge it.
* Say that ECH adds a new kind of Padding handshake message, which the sender can incorporate into the handshake as needed, and the receiver ignores.

If we leave ECH as-is, it seems to me QUIC (both spec and implementations) needs some changes to track padding across retransmission.

**Comment by chris-wood** [comment]
(2) seems simplest and most useful to me. The receiver path is trivial, and avoiding per-message semantics for adding padding (or not, if the extension isn't supported) seems easier. (This would also let clients move inner CH padding from an extension to a message, which might simplify padding calculations in the case where binders are used? That is, it can pad a fully-formed CH, rather than only part of a CH.)

**Comment by martinthomson** [comment]
The alternative is to tell the QUIC stack to pad, in the same way that TLS is told to pad.  This is more complicated in QUIC, because you have to respect packet boundaries and ensure that you include ack-eliciting frames in packets that might other contain only padding, but it is doable.

This is not by any means perfect, but it matches the signals in TLS.  The handshake tells the record layer: "pad to X".

**Comment by kazuho** [comment]
My +1 goes to padding at the handshake message level.

Padding at the record layer (or QUIC packet layer) is going to require more work and have more security concerns, as the transport needs to pad retransmissions.

As an example, when a handshake message that requires padding is split into multiple packets, and one of the packets gets lost, the transport has to figure out what to send and how to pad. In case of QUIC, we also have to make sure that PING frame would be used when the only thing that has to be retransmitted is padding, because not sending an ack-eliciting packet would reveal to a passive observer that it was padding only.

**Comment by martinthomson** [comment]
An alternative to a Padding message is to use the existing padding extension (in Certificate or EncryptedExtensions or both) to ensure that the overall message is the right size.  That accomplishes the goal, but it does require that the client be willing to send it, or we create a new exception to the rules for extensions.  You could, I guess, add the padding to the ECH extension.

New messages cost more (than I'd like).

**Comment by davidben** [comment]
I just realized a nuisance with the extensions option: certificate extensions are incompatible with draft-ietf-tls-certificate-compression, which is [important for QUIC](https://www.fastly.com/blog/quic-handshake-tls-compression-certificates-extension-study). The extension compresses the entire Certificate message, so any padding messages inside the payload would get compressed away.

We could still fudge this by computing how much padding would be needed ahead of time and then adjusting the padding in EncryptedExtensions (same flight and all), but this is getting pretty silly. :-)

An aside since this comes up alot: ECH and certificate compression are perfectly compatible. Rather than padding up to `max(len(cert) for cert in anonymity_set)`, you pad the compressed cert up to `max(len(compress(cert)) for cert in anonymity_set)`. The key observation is that, assuming compression support is uniform across the anonymity set, *whether* you compressed is not sensitive, only *what* you compressed.

> New messages cost more (than I'd like).

Huh, I'd actually seen the extension as more annoying, since we'd need to add quirks to the unsolicited extensions rule. Is the issue for you all the state machine integration or something else? (I was envisioning we'd just have the handshake message logic silently drop all the padding messages on the ground so the handshake state machine doesn't notice.)

**Comment by cjpatton** [comment]
From the interim meeting, it seems folks are not enthusiastic about doing padding in the record layer. We still need a proposal for doing padding in the handshake.

**Comment by ekr** [comment]
As I was saying on the call, what I propose is:

1. The client pads with the RFC 7685 padding extension in CHInner
2. The server pads in EE with RFC 7685 padding

We would then relax the restriction on servers sending padding in 7685 Section 3 but not the restriction on unsolicited extensions.

There is a minor inconvenience here in that you would be required to compute the amount of padding needed before sending EE (because it appears prior to Certificate).

**Comment by davidben** [comment]
(Oof, I got confused by time zones and thought the call was much later in the day.)

Precomputing the padding in EE would probably work, if a bit obnoxious to implement on the sender's side. It also doesn't allow padding the client certificate, if the client wishes to hide some information on that end.

**Comment by chris-wood** [comment]
> It also doesn't allow padding the client certificate, if the client wishes to hide some information on that end.

Yeah, I'd like there to be a mechanism for supporting this on the client side. Something that only works for one end doesn't seem like the best solution here.

**Comment by ekr** [comment]
Agreed that it doesn't allow padding the client cert, however, this issue already exists in TLS 1.3 w/o ECH. My proposal for that would be the dual of this: include the padding extension in CR and then pad in CERT.

**Comment by kaduk** [comment]
> Agreed that it doesn't allow padding the client cert, however, this issue already exists in TLS 1.3 w/o ECH. My proposal for that would be the dual of this: include the padding extension in CR and then pad in CERT.

Just to check my understanding: this is predicated on fixing the interaction of CERT and compression w.r.t. preserving padding, right?

**Comment by davidben** [comment]
(@vasilvv FYI.) Certificate compression already got a code point allocated June 2018 and went through WGLC April 2019. That code point's shipped for some time now. So if we're to change anything there, we'd at minimum need to burn the old code point and get a new one.

(I'm not opposed to doing that if it's the right path forward. Just wanted to make sure folks were aware of the complication.)

What fix are folks envisioning?

**Comment by chris-wood** [comment]
From the interim: stick with EE for padding, and address the client-side padding issue separately (as a change to ALPS or a new handshake message type).

**Comment by cjpatton** [comment]
Hi issue, I'm working on a PR for server-side padding (using EE) now. Will post a link once it's ready.

**Comment by cjpatton** [comment]
Two questions.
1. RFC 7685 only specifies the usage of the padding extension in the ClientHello. Will ECH need to update the IANA registry to allow the extension to appear in EncryptedExtensions?
1. RFC 7685 mandates that the server MUST NOT echo the extension. We need to amend this rule here. What's the best way to do so? A couple options:
       (a) "The server MAY echo the padding extension in its EncryptedExtensions message".

**Comment by cjpatton** [comment]
For (d) I'm not sure what to do about this (RFC8446, 4.3.1): 
>    The EncryptedExtensions message contains extensions that can be
   protected, i.e., any which are not needed to establish the
   cryptographic context but which are not associated with individual
   certificates.  The client MUST check EncryptedExtensions for the
   presence of any forbidden extensions and if any are found MUST abort
   the handshake with an "illegal_parameter" alert.

For clients who don't know now the new rule, an unsolicited extension cause an abort, no?

**Comment by cjpatton** [comment]
Note that the standard Go implementation (crypto/tls) does not appear to enforce this "MUST": see `readServerParameters()` in https://golang.org/src/crypto/tls/handshake_client_tls13.go.

**Comment by davidben** [comment]
BoringSSL does. But yes (d) would contradict the no unsolicited extensions rule and would need some text to undo it (as is already done for the cookie extension in HRR).

The no unsolicited extensions rule is really an approximation of a more subtle rule: the server can only send things in EncryptedExtensions that it knows the client will understand. The client can expect to full parse the entirety of EncryptedExtensions.

No matter how we slice it, this is a change to the wire protocol. Changes to the wire protocol require flavor of negotiation, so we retain compatibility with existing implementations.

**Comment by richsalz** [comment]
I think C makes more sense.  The code changes, let alone the wording changes, for it seem more clean and simple.

**Comment by cjpatton** [comment]
I tend to agree with @richsalz, though I think @davidben's idea is very doable. I think the trade off is cleanliness (c) vs not defining a new codepoint (d). I'm not sure what's more important.

**Comment by chris-wood** [comment]
I'd go for (c). I think code points are (intentionally) cheap, so we might as well use them.

**Comment by davidben** [comment]
(c) SGTM. And yeah I agree it's probably less fuss.

Since the inner CH should have padding anyway, perhaps the ClientHello extension should not just solicit padding but also just contain padding as before. Then we're effectively dropping ECH's dependency on RFC7685 and moving it to a more general padding extension.

**Comment by cjpatton** [comment]
I like that idea.

**Comment by cjpatton** [comment]
Alrighty,  https://github.com/tlswg/draft-ietf-tls-esni/pull/313 is my attempt to spell (c) with @davidben's suggestion of dropping dependency on RFC7685. I look forward to your feedback.

**Comment by chris-wood** [comment]
Closing per discussion at IETF 118. The concrete proposal here is to define the desired padding mechanism in a separate draft, be it one based on a handshake message, extension, or more details about how to do this at the record layer.
