### ISSUE TITLE
Computation of `config_digest`: which KDF?

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#278]
The `config_digest` field is defined as;
> A cryptographic hash of the ECHConfig structure from which the ECH key was obtained, i.e., from the first byte of "version" to the end of the structure. This hash is computed using the hash function associated with cipher_suite, i.e., the corresponding HPKE KDF algorithm hash.

But the `ECHConfig` structure in draft-07 specifies a list of KDF/AEAD pairs. So which KDF is used to compute `config_digest`? The client is supposed to ignore any KDF/AEAD it doesn't support, so it's not clear how a client and server who need to negotiate the cipher suite can compute `config_digest` correctly.

**Comment by cjpatton** [comment]
One way to solve this problem is to only allow one cipher suite per ECH configuration.

**Comment by davidben** [comment]
I think one cipher suite per ECH configuration is a step too far in flattening. While juggling lots of KEM algorithms is unlikely (we basically have one correct answer right now, and each KEM algorithm is another long-lived key to manage), cipher suites are easier to shuffle and there are multiple correct answers depending on hardware capabilities. Whether AES-GCM and ChaCha20-Poly1305 is preferred is complex.

Perhaps we use KDF associated with the KEM instead?

**Comment by cjpatton** [comment]
Hmm, doesn't the cipher suite list indicate a set of KDFs that MAY be used with the KEM? In other words, if there's a KDF associated with the KEM, then why would we allow multiple KDFs?

**Comment by davidben** [comment]
Ah hrm. I had thought the KEM had a KDF associated, but looks like that's not quite right. The KEM interface does not, but the DHKEM happens to internally use a KDF, which may or may not be the same as the HPKE-level one.

**Comment by chris-wood** [comment]
Right -- KEMs might not have KDFs associated with them. I think we should just use the KDF that the client picks when encrypting the ClientHello:

~~~
    struct {
       HpkeCipherSuite cipher_suite; // <--- the KDF specified here...
       opaque config_digest<0..2^16-1>; // <--- ... is used to compute this value
       opaque enc<1..2^16-1>;
       opaque encrypted_ch<1..2^16-1>;
    } ClientEncryptedCH;
~~~

It's fine that the ECHConfig has a list of KDFs. The client picks only one and tells the server which one. And I think it's reasonable for the server to be able to compute the `config_digest` (or whatever we rename it to be) with the KDF of the client's choosing.

**Comment by cjpatton** [comment]
That's workable, although it does lead to a bit of a combinatorial explosion. Suppose the server has two ECH configurations, `config1` and `config`, each supporting HKDF-SHA256 and HKDF-SHA256 for the KDF, but only AES-GCM for the AEAD. To avoid trial hashing to determine which configuration to use, the server will need to store a data structure like this:
```python
{
   config1_digest_hkdf_sha256_aes_gcm: config1,
   config1_digest_hkdf_sha512_aes_gcm: config1,
   config2_digest_hkdf_sha256_aes_gcm: config2,
   config2_digest_hkdf_sha512_aes_gcm: config2,
}
```

In general, if there N configurations, each supporting k KDFs and e AEADs, then there are N * k * e entries in this table.

**Comment by chris-wood** [comment]
Yeah, there's more state on the server, but that seems to be the price of supporting multiple configurations.

**Comment by davidben** [comment]
> In general, if there N configurations, each supporting k KDFs and e AEADs, then there are N * k * e entries in this table.

Does the server need a separate entry for each AEAD, or just each KDF? I thought we were just extracting a hash function out, which would suggest just the KDF. (Unlike AEADs, which need to deal with the mess around AES, I think there's a lot less reason for a server to particularly care about KDF diversity.)

**Comment by cjpatton** [comment]
Ohh duh :) It should be N * c, where c is the number of cipher suites.

**Comment by davidben** [comment]
Shouldn't it be N * h, where h is the number of distinct `HpkeKdfId`s in your `HpkeCipherSuite`s? That is, if you support AES-GCM and ChaCha20-Poly1305, but only pair them with HKDF-SHA256, you only need one hash. Although, looking at ECHConfig again, the association between AEAD and KDF is a purely ECH-level construct. So we could choose to disassociate them and then flatten:

```
       struct {
           opaque public_name<1..2^16-1>;

           HpkePublicKey public_key;
           HpkeKemId kem_id;
           HpkeKdfId kdf_id;
           HpkeAeadId aead_ids<2..2^16-2>;

           uint16 maximum_name_length;
           Extension extensions<0..2^16-1>;
       } ECHConfigContents;
```

Now there's no multiplication. That said, flattening to this level and not other levels assumes you believe that `HpkeKdfId` diversity is rare (personally I'd have been happy just locking all of TLS 1.3 onto HKDF-SHA256 and bumping versions for a KDF swap) while `HpkeAeadId` diversity is meaningful (the AES hardware silliness).

**Comment by chris-wood** [comment]
That's an interesting suggestion. I don't see why one would choose a KDF other than HKDF-SHA-256, at least in the near term.

**Comment by martinthomson** [comment]
Well, the obvious thing to do in the near term is switch to a KDF that is a little faster than HKDF.

The other thing I notice here is that with this change you don't need `config_digest` to be variable-length.

**Comment by chris-wood** [comment]
We don’t yet have any standard KDFs that would fit the bill, do we?

**Comment by martinthomson** [comment]
No, but I still carry a flame for getting one.  HKDF is a rock, but it's a heavy one.

**Comment by cjpatton** [comment]
I would also like to see alternatives to HKDF. There seem to be a lot of interesting alternatives floating around.

**Comment by cjpatton** [comment]
I think the resolution to this issue is to keep the spec as is:

> config_digest                                                                                                               
: Equal to `Expand(Extract("", config), "ech_config_digest", Nh)`, where
`config` is the `ECHConfig` structure and `Extract`, `Expand`, and `Nh` are as
specified by the cipher suite KDF. (Passing the literal `""` as the salt is
interpreted by `Extract` as no salt being provided.)
 
Let's close this issue if there's no objection.
