### ISSUE TITLE
When computing config_digest, use I2OSP on integer values.

### ISSUE THREAD

**Issue by kjacobs-moz** [tlswg/draft-ietf-tls-esni#280]
`config_digest` is defined as `A cryptographic hash of the ECHConfig structure from which the ECH key was obtained, i.e., from the first byte of "version" to the end of the structure.`

As the struct contains integer values, those fields should first be normalized with I2OSP. Also, it's probably worth clarifying that the hash is taken over the serialized representation of the struct.

**Comment by davidben** [comment]
I don't think that's right for a TLS structure. TLS already has well-defined serialization, which is what that structure uses. See https://tools.ietf.org/html/rfc8446#section-3

**Comment by kjacobs-moz** [comment]
Ah - that's right. Coming from HPKE this looked like a gap, but I think it's well-defined in this context. Thanks.

**Comment by chris-wood** [comment]
Closing as resolved.
