### ISSUE TITLE
ServerEncryptedCH: retry_configs vs. retry_keys

### ISSUE THREAD

**Issue by kjacobs-moz** [tlswg/draft-ietf-tls-esni#281]
The spec uses both `retry_configs` and `retry_keys` when referring to the contents of `ServerEncryptedCH`. These should be made consistent (preferably using the former).

**Comment by chris-wood** [comment]
Agreed -- let's unify around `retry_configs`!

**Comment by davidben** [comment]
(`retry_keys` is a remnant of the old `ESNIKeys` name. I guess we missed a few.)
