### ISSUE TITLE
Section number levels

### ISSUE THREAD

**Issue by MikeBishop** [tlswg/draft-ietf-tls-esni#284]
Purely editorial, but the layout of the TOC is a bit confusing....

> 1.  Introduction
> 2.  Conventions and Definitions
> 3.  Overview
> 3.1.  Topologies
> 3.2.  Encrypted ClientHello (ECH)
> 4.  Encrypted ClientHello Configuration
> 4.1.  Configuration Extensions
> 5.  The "encrypted_client_hello" extension
> 6.  The "ech_nonce" extension
> 6.1.  Incorporating Outer Extensions

I think all the confusing things about this would be resolved by moving "encrypted_client_hello" and "ech_nonce" to be subsections of 4.1, instead of top-level sections in their own right.  This would make 6.1 become 4.2, and "Incorporating Outer Extensions" does seem like a reasonable sub-section of "Encrypted ClientHello Configuration".

**Comment by chris-wood** [comment]
The order is much cleaner now. It describes, in order: the ECH configuration details, extension details, client behavior, and then server behavior. @MikeBishop, I'd suggest closing this as resolved. What do you think?

>   1.  Introduction  . . . . . . . . . . . . . . . . . . . . . . . .   3
>   2.  Conventions and Definitions . . . . . . . . . . . . . . . . .   4
>   3.  Overview  . . . . . . . . . . . . . . . . . . . . . . . . . .   4
>     3.1.  Topologies  . . . . . . . . . . . . . . . . . . . . . . .   4
>     3.2.  Encrypted ClientHello (ECH) . . . . . . . . . . . . . . .   5
>   4.  Encrypted ClientHello Configuration . . . . . . . . . . . . .   7
>     4.1.  Configuration Extensions  . . . . . . . . . . . . . . . .   8
>   5.  The "encrypted_client_hello" extension  . . . . . . . . . . .   9
>     5.1.  Incorporating Outer Extensions  . . . . . . . . . . . . .  10
>   6.  Client Behavior . . . . . . . . . . . . . . . . . . . . . . .  11
>     6.1.  Sending an encrypted ClientHello  . . . . . . . . . . . .  11
>     6.2.  Recommended Padding Scheme  . . . . . . . . . . . . . . .  13
>     6.3.  Handling the server response  . . . . . . . . . . . . . .  14
>       6.3.1.  Accepted ECH  . . . . . . . . . . . . . . . . . . . .  14
>       6.3.2.  Rejected ECH  . . . . . . . . . . . . . . . . . . . .  14
>       6.3.3.  HelloRetryRequest . . . . . . . . . . . . . . . . . .  16
>     6.4.  GREASE extensions . . . . . . . . . . . . . . . . . . . .  16
>   7.  Server Behavior . . . . . . . . . . . . . . . . . . . . . . .  17
>     7.1.  Client-Facing Server  . . . . . . . . . . . . . . . . . .  17
>     7.2.  Backend Server Behavior . . . . . . . . . . . . . . . . .  19

**Comment by MikeBishop** [comment]
That's probably workable.
