### ISSUE TITLE
Possible to simplify interaction with session resumption?

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#285]
The current draft contains various rules around ECH and resumption.

> Per {{client-behavior}} and {{server-behavior}}, implementations are required to track, alongside each PSK established by a previous connection, whether the connection negotiated this extension with the "ech_accept" response type. If so, this is referred to as an "ECH PSK". Otherwise, it is a "non-ECH PSK". This may be implemented by adding a new field to client and server session states.

> When offering an encrypted ClientHello, the client MUST NOT offer to resume any non-ECH PSKs.

> If the server resumed a session or negotiated a session that did not use a certificate for authentication, the client MUST abort the connection with an "illegal_parameter" alert. This case is invalid because {{send-ech}} requires the client to only offer ECH-established sessions, and {{server-behavior}} requires the server to decline ECH-established sessions if it did not accept ECH.

> The server MUST ignore all PSK identities in the ClientHello which correspond to ECH PSKs. ECH PSKs offered by the client are associated with the ECH name. The server was unable to decrypt then ECH name, so it should not resume them when using the plaintext SNI name. This restriction allows a client to reject resumptions in {{auth-public-name}}.

> If the server sends a NewSessionTicket message, the corresponding ECH PSK MUST be ignored by all other servers in the deployment when not negotiating ECH, including servers which do not implement this specification.

These rules date to before we started encrypting the entire ClientHello and were intended to avoid mixing up session resumptions between the public and private name, since the same pre_shared_key extension was used for both, and amount to saying implementations must add a boolean to their session state.

Now that the public and private names correspond to different ClientHellos altogether, the client can (and should) only send inner name tickets in the inner ClientHello and outer name tickets in the outer ClientHello. (#270) I suspect that means we no longer need further ECH special cases here.

**Comment by chris-wood** [comment]
This seems like a good simplification, but we should probably be careful about the interaction with cross-SNI resumption.

**Comment by davidben** [comment]
I think it just composes as expected? If you offer a PSK in the outer ClientHello, cross-SNI or no, it means that you are satisfied with it as an alternative to the certificate covering the public name. If you offer a PSK in the inner ClientHello, cross-SNI or no, it means you are satisfied with it as an alternative to the certificate covering the true name. Your ClientHellos should be consistent with this, which means that servers resuming isn't an issue.

TBH I forgotten some of the details for why this was here. I found this long comment I wrote, but apparently past me was just unsatisfied that a case (4) was "weird". So that was very unhelpful, past me. Regardless, I think the ambiguity is moot now.
https://github.com/tlswg/draft-ietf-tls-esni/pull/124#discussion_r243055936

(I also expect clients just won't offer PSKs in the outer ClientHellos. It's unlikely that you'll get any to offer anyway. And if your API has an external session cache, the caller needs to go out of their way to do two lookups.)

**Comment by chris-wood** [comment]
I was thinking about clients that might mistakenly use inner tickets for the outer name when given the cross-SNI signal. (I agree that it composes naturally.) A simple note would probably suffice. 

For outer tickets, I tend to think they should just discouraged. What's the benefit of resuming a TLS 1.3 connection you'd tear down anyway?

**Comment by cjpatton** [comment]
I'm not sure I fully understand the (historical) need to distinguish between ECH-PSKs and non-ECH-PSKs. But why would a client offer PSK to a client-facing server at all? In other words, will it ever be useful to use send a PSK extension in the ClientHelloOuter? It seems to me that this feature is only meaningful to the intended backend server, and so should only appear in the ClientHelloInner.

The same question applies to all other extensions. If the client-facing server terminates the connection, then the only action the client will take is to close the connection. Hence, the only functionality we will ever need for the client<->client-facing server connection is to complete a full, server-authenticated handshake. If I were implementing the client, I would restrict the contents of the ClientHelloOuter to only those extensions that are necessary to implement this functionality. I wonder if it makes sense to enforce this in the spec. Something like: "When offering the 'ech' extension, the client MAY include the following extensions in the ClientHelloOuter: 'supported_versions', 'server_name'. 'key_shares', 'signature_algorithms', [and so on]. It MUST NOT include any other extensions."

What are the downsides to doing something like this? I think the upside is that it simplifies the problem of deciding what to put in the ClientHelloInner versus the ClientHelloOuter. I suppose one problem is that it potentially sticks out a bit.

**Comment by chris-wood** [comment]
Based on this week's interim, we decided it was fine to prohibit PSKs in the outer CH for ECH connections, so the current draft text prohibits "pre_shared_key" extensions in the outer CH. A connection using GREASE may, however, decide to resume its connection to the outer name. This gives a passive adversary a pretty easy distinguisher between GREASE and non-GREASE: if there's a ticket present, the connection is definitely GREASE. 

It *seems* that if we want to maintain our current indistinguishability properties, there always needs to be some ticket. So perhaps that means:

- ECH (non-GREASE) clients would generate a bogus (GREASEd) ticket
- GREASE clients that don't have a ticket would generate a bogus ticket
- GREASE clients that have a ticket would use it

@davidben, @ghedo, @ekr, @martinthomson, @cjpatton: penny for your thoughts?

**Comment by davidben** [comment]
I mostly figure there won't be a ticket in the initial connection to a server, or any connections made after long time, so intolerance to ticket-less ClientHellos will likely be noticed quickly. Though it is true that probably a lot of connections offer tickets.

There may be something to be said for allowing clients to send bogus tickets if they want, but it's worth noting an active attacker can tell if the ticket is (most likely) bogus by simply trying to resume it.

(A tangent: we actually saw a very old TLS 1.0 server implementation that broke with TLS 1.3 because it would take the client's session IDs and unconditionally echo it back. I'm not sure what was going on there. It didn't actually switch to a resumption handshake or implement resumption at all. It just echoed back the session ID for some reason. Only reason this didn't break before was that it never issued session IDs, so this codepath had never been tested before.)

**Comment by chris-wood** [comment]
> There may be something to be said for allowing clients to send bogus tickets if they want, but it's worth noting an active attacker can tell if the ticket is (most likely) bogus by simply trying to resume it.

True, but that's already the case for active attackers. What I'm concerned about are passive attackers.

**Comment by cjpatton** [comment]
I think this gets at a larger "don't stick out" problem currently only addressed in bits and pieces. Just as dummy (i.e., greased) ECH is used to provide covertext for real ECH, real-ECH connections also need to provide covertext for the real extensions offered in dummy-ECH connections. In particular, the spec should provide guidance on how to generate dummy extensions in the ClientHelloOuter.
