### ISSUE TITLE
What to do on ECH decryption failure?

### ISSUE THREAD

**Issue by Lekensteyn** [tlswg/draft-ietf-tls-esni#290]
Two sections suggest to ignore the extension on decryption failure, but one suggests to send an alert. What should happen?

Ignoring the extension on unrecognized `config_digest` failures sounds reasonable in order to "not stick out". However, it is not entirely unambiguous what to do if a valid ECHConfig is found but decryption fails.

[3.2. Encrypted ClientHello (ECH)](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#section-3.2) says:

> Upon receiving the ClientHelloOuter, the client-facing server takes one of the following actions:
> [..]
> 3. If it supports ECH but cannot decrypt it, then it ignores the extension and proceeds with the handshake as usual.

[7.3.2.1. Authenticating for the public name](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#section-7.3.2.1) says:

> When the server cannot decrypt or does not process the "encrypted_client_hello" extension, it continues with the handshake using the plaintext "server_name" extension instead (see Section 8).

[8. Client-Facing Server Behavior](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#section-8) says:

> If the ClientEncryptedCH value matches a known ECHConfig, the server then decrypts ClientEncryptedCH.encrypted_ch, [..]
> If decryption fails, the server MUST abort the connection with a "decrypt_error" alert.

**Comment by cjpatton** [comment]
I think the first two statements apply when the config_digest doesn't correspond to a known ECHConfig; the last is when the ECHConfig is known, but decryption fails. The text could be a lot clearer here.

**Comment by ekr** [comment]
@cjpatton Yes, your interpretation is correct. I think this is the result of a number of uncoordinated changes.

**Comment by chris-wood** [comment]
Closing as resolved.
