### ISSUE TITLE
Greasing to supporting servers

### ISSUE THREAD

**Issue by wbl** [tlswg/draft-ietf-tls-esni#295]
@cjpatton and I were sitting down and thinking and we realized the following scenario can happen:

1. example.com is on hosting.com, which supports ECH
1. example.com has an HTTPS record, an A record, AAAA record pointing at the IP for hosting.com
1. A user of a browsers latest release that supports ECH and greases the extension is using a resolver that doesn't resolve HTTPS records

This results in an ECH request being made with SNI=example.com, and a rejection of the ECH. So now the question is what the client should do and what should servers expect?
* Try again, with the outer SNI the one matching the one in the new config
* Use the connection authoritatively for example.com since the connection has already revealed the issue.

**Comment by davidben** [comment]
The intention was the latter, but the text could probably be clearer. I don't think there's much point in trying again since the name has already been revealed. See https://github.com/tlswg/draft-ietf-tls-esni/issues/274#issuecomment-680182501

**Comment by chris-wood** [comment]
@wbl is this still an issue now that #287 is merged?

**Comment by wbl** [comment]
I think the client behavior remains equally unspecified. In particular the lengthy argument @cjpatton and I had about server enforcement of the client behavior I think isn't changed.

**Comment by cjpatton** [comment]
Care to file a PR, presuming the latter behavior is intended?

**Comment by cjpatton** [comment]
A proposed resolution is here: #319.

**Comment by cjpatton** [comment]
@wbl, a proposed fix has been merged. See #321.

**Comment by wbl** [comment]
I think this text works.
