### ISSUE TITLE
Proposal: Add version indication to ClientEncryptedCH

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#297]
The ECH version is negotiated as follows: the server indicates which versions of ECH it supports by advertising a configuration for each supported version, and the client selects the version by selecting a configuration. The selected configuration is currently indicated by `ClientEncryptedCH.config_digest`.

The `ClientEncryptedCH` structure is defined as follows:
```
      struct {
          HpkeCipherSuite suite;
          opaque config_digest<0..2^16-1>;
          opaque enc<1..2^16-1>;
          opaque encrypted_ch<1..2^16-1>;
      } ClientEncryptedCH;
```

Because the negotiated version is determined by the configuration, future versions of ECH that change the structure of `ClientEncryptedCH` --- in particular, the way the selected configuration is indicated--- will break backwards compatibility. Therefore, I would like to propose adding the ECH version to to this structure.

**Comment by davidben** [comment]
Oh nice catch. I agree that the versioning scheme doesn't work here, though our experience adding extension points inside extension points has not been good. Implementations keep messing them up and we lose the extension point anyway. ("Have one joint and keep it well-oiled.")

Do we actually need the versioning scheme after the draft is done? If it weren't for the SVCB code point, I would say we should simply pick different extension code points for each deployed draft. But perhaps we should just do that for the SVCB code point too? If we did that, would we need versions in the first place?

**Comment by ekr** [comment]
Well, strictly speaking they will only do so if they break the first two fields, right? Because the rest can be conditioned on the config_digest.

**Comment by cjpatton** [comment]
True, but to @davidben's point, I wonder if versioning ECHConfigContents is necessary.

**Comment by cjpatton** [comment]
Unless we advertise the version here, we're committing to the first two fields being the same in future versions. Unless we anticipate these changing, let's stick with the status quo.

**Comment by bemasc** [comment]
Each HPKE suite has a fixed-length key encapsulation (`Nenc`), so the length field of `enc` is redundant.  If we concatenate `enc` and `encrypted_ch` into a single opaque field, that might be more future-proof.

**Comment by cjpatton** [comment]
I don't see how that helps, since the fields that can't change are cipher_suties and config_id.

**Comment by cjpatton** [comment]
By way of addressing this issue, I've created a PR that "locks" ECHConfig.version to the extension code point. https://github.com/tlswg/draft-ietf-tls-esni/pull/303

This provides an unambiguous signal of which version of ECH is selected by the client

**Comment by cjpatton** [comment]
I'm not sure the choice of code point (ff08) is available. I picked it because it reflects the next draft (08).
