### ISSUE TITLE
legacy_session_id should match between inner and outer

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#310]
If the client uses TLS 1.3's [middlebox compatibility mode](https://tools.ietf.org/html/rfc8446#appendix-D.4), there are a couple subtle points:

* Even though the middlebox will never see the inner ClientHello, we still need a non-empty legacy_session_id, because some servers use that value to condition the other bits.

* More importantly, the inner legacy_session_id needs to match the outer legacy_session_id! Otherwise the server will echo back the wrong one and trip up all the buggy middleboxes again.

Alternatively, we could say the server uses the outer ClientHello to negotiate middlebox compatibility mode. That would reduce bytes on the wire, but it'd upset all the split mode arrangements.

**Comment by chris-wood** [comment]
Good catch. I'd be fine with this matching constraint. Could you please propose text?
