### ISSUE TITLE
Re-re-visit outer ClientHello binding (saves 65 bytes)

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#323]
We previously decided not to bind the outer ClientHello to the ECH decryption, because doing so is rather a hassle. We'd need something similar to the TLS 1.3 PSK binder mess, with the added complexity of ordering relative to the PSK binders themselves. Additionally, while the binding helps with some of the don't stick out properties, there were other attacks on distinguishability anyway. So, instead, we mitigated the inner ClientHello malleability with OuterExtensions.inner_digest and left the outer ClientHello unbound.

However, we've since decided not to allow PSKs in the outer ClientHello. Perhaps we should revisit this. Suppose the AD parameter to the ECH decryption were the entire outer ClientHello, minus the ECH extension. I believe this means we no longer need OuterExtensions.inner_digest. That would give an immediate 33-byte savings. It would then unlock a further 32 byte savings by amending #312 to say:

* Client always encodes an empty legacy_session_id in ECH plaintext.
* Client-facing server copies outer legacy_session_id to inner ClientHello as part of decompression.

(The reason we can't do this easily right now is that, if the inner ClientHello lacks outer_extension, nothing's authenticating legacy_session_id. Since the field in TLS 1.3 is all but ignored, it's "obvious" that the malleability doesn't matter, but it's nicer to not need to think about such things.)

From looking at Chrome's ClientHellos and working through what we'd send (drop 1.2-only extensions, compress most), it looks like the inner ClientHello will be maybe 130-140 bytes, plus a padded server_name. The 65 bytes above would almost halve the overhead.

In some sense what's going on here is our 16-byte tag on the AEAD in the ECH ciphertext is going to waste. We didn't authenticate everything that goes into reconstructing the inner ClientHello (outer_extensions), so instead we authenticate another hash (OuterExtensions.inner_digest) and check that afterwards. (To that end, if we do this, we probably need to say the server MUST reject encrypted_client_hello showing up in outer_extensions, that way all inputs to decompression are authenticated. Equivalently, decompression is done relative to the ECH-extension-less AD input rather than the original outer ClientHello.)

**Comment by cjpatton** [comment]
I like this idea. How do you think the AD ought to be structured? The ClientHelloOuter, but with an an empty "encrypted_client_hello" extension?

**Comment by davidben** [comment]
Yeah, that's seems the simplest to me. Filling it with zeros, as @bemasc pointed out to me, requires predicting the length of the encrypted inner ClientHello. This isn't strictly impossible (ADs don't change ciphertext length), but it seems needlessly fussy and ECH is already requiring we be able re-encode ClientHellos, lengths and all.

Note this assumes there are no computed PSK binders in the outer ClientHello because otherwise there's a circular dependency. (If we wanted to allow that, the AD would need to zero/trim the binders or so.)

**Comment by davidben** [comment]
Another benefit is it stops the attacker from probing information about compressed extensions. Currently an attacker can learn which extensions are compressed in the inner ClientHello by removing them from the outer ClientHello and seeing if the server still responds. This isn't a huge deal, as compressed extensions are assumed public, but this way we remove that vector and leave only the fuzzier signal from the ciphertext length.

**Comment by davidben** [comment]
> Filling it with zeros, as @bemasc pointed out to me, requires predicting the length of the encrypted inner ClientHello. This isn't strictly impossible (ADs don't change ciphertext length), but it seems needlessly fussy and ECH is already requiring we be able re-encode ClientHellos, lengths and all.

On second thought, a lot of implementations will need to do that prediction anyway. The workaround for the old F5 bug means we'll need to know the eventual size for the padding extension. (On the other hand, you can probably assume anyone doing ECH is not running those things. On the other hand, turning off the workaround would stick out.) Ah well. We did it for PSK already.

(I wonder if we can do drop that workaround now that TLS 1.0 and 1.1 are gone...)

**Comment by cjpatton** [comment]
What's the "old F5 bug"?
What's the value in authenticating the length of the "encrypted_client_hello" extension? This is authenticated by the handshake already, no?

**Comment by davidben** [comment]
> What's the "old F5 bug"?

https://www.imperialviolet.org/2013/10/07/f5update.html
https://mailarchive.ietf.org/arch/msg/tls/8wXwhM1d5WSmROHFSgrTyFmWN2o/
It's why we have a padding extension.

> What's the value in authenticating the length of the "encrypted_client_hello" extension? This is authenticated by the handshake already, no?

There isn't. It's just a question of what's easier to deal with. Filling it with zeros means that, when computing the AD, you don't need to fully reconstruct a modified outer ClientHello with updated length prefixes. We avoided this when computing the PSK binder in RFC8446.

It's a mild hassle but not a huge deal. But the F5 padding business does mean computing this binder will likely take some length prediction, but so it goes.

**Comment by cjpatton** [comment]
I agree, it's not a big hassle.

**Comment by chris-wood** [comment]
> I like this idea. How do you think the AD ought to be structured? The ClientHelloOuter, but with an an empty "encrypted_client_hello" extension?

Rather than make the extension empty, can we just omit the `enc` and `payload` fields? (The `cipher_suite` and `config_id` should arguably be included, a la #326).

**Comment by davidben** [comment]
That works, though it's even more fussy for the client to construct, since it needs to half-encode the ECH extension before fully encoding it.

`cipher_suite` is already bound into HPKE itself. `config_id` is less clear, but I thought our model already said all this didn't matter? Isn't the binding here just to replace `inner_digest` and provide malleability? If there's something more going on, I'd like us to have some principled answer here, so we can answer questions like... what about the handshake transcript, which may not be empty on HRR? If we do that, what's going on with ech_hrr_key?

**Comment by chris-wood** [comment]
The principle I was following is: include as much as possible in the AD. Yeah, it's more of a pain, and we've gotten away with *no* binding whatsoever up to now, so maybe we don't need it. I'm happy to start with an empty ECH extension and then consider the other parts later, if that'll help.

**Comment by davidben** [comment]
I don't feel very strongly either way.

**Comment by chris-wood** [comment]
Let's just do the simpler thing now, then! :-)
