### ISSUE TITLE
Clarify that CHInner ECH payload contents

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#324]
Unless I missed it, nowhere in the spec does it say that clients SHOULD/MUST send an empty ECH extension in CHInner (to trigger the confirmation signal). Should we add this?

cc @davidben, @cjpatton

**Comment by cjpatton** [comment]
This is covered in Section 5: 
> When offering the "encrypted_client_hello" extension in its ClientHelloOuter, the client MUST also offer an empty "encrypted_client_hello" extension in its ClientHelloInner, wherever applicable. (This requirement is not applicable when the extension is generated as described in Section 6.4.)

**Comment by chris-wood** [comment]
Ah, thank you! Closing.
