### ISSUE TITLE
Encoded vs actual ClientHelloInner is a little ambiguous

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#331]
There are two ClientHelloInners, the actual one used in the handshake, and the encoded one with outer_extensions substituted in. Both are described as ClientHelloInner, but this makes it slightly ambiguous which goes into, say, the handshake transcript.

(It's late now, so I'll leave this as an issue without a PR. If we don't end up resolving this separately, I'll probably fix this as part of #323. If we decide to implicitly copy over legacy_session_id, the encryption payload becomes less and less defensibly an actual ClientHelloInner.)

**Comment by cjpatton** [comment]
In my own implementation, I've been referring to the plaintext payload as CompressedClientHelloInner. Which is terrible, but unambiguous.

**Comment by davidben** [comment]
Works for me. I was thinking EncodedClientHelloInner because it's shorter and still works even if you choose not to compress anything. (A no-op encoding is still an encoding.)

**Comment by chris-wood** [comment]
+1 to EncodedClientHelloInner, given that compression is optional. @davidben, if you have time, could you whip up a PR?
