### ISSUE TITLE
Stateless HRR and split mode

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#333]
I was thinking about #316 and the discussion on server HRR checks started by https://github.com/tlswg/draft-ietf-tls-esni/issues/325#issuecomment-705796082, and I'm not sure HRR cookies even work in split mode right now. First off, suppose we don't merge something like #316. The current text says:

> Note: if the inner and outer ClientHellos use different groups for
> their key shares or differ in some other way, then the HelloRetryRequest may	
> actually be invalid for one or the other ClientHello, in which case a fresh	
> ClientHello MUST be generated, ignoring the instructions in HelloRetryRequest.	
> Otherwise, the usual rules for HelloRetryRequest processing apply

This means if you get a cookied HRR only good for ClientHelloInner, there's no requirement to stick the cookie in ClientHelloOuter! But now the client-facing server can't see the cookie, so it can't be stateless. It would seem like #316 fixes this, but now we have a more fundamental problem: whose cookie?

Suppose the client-facing server wishes to handle HRR statelessly. It decrypts the first ClientHelloInner and forwards it to the backend server. If the backend server responds with HRR, the client-facing server must forward the HRR as-is, or the transcript breaks. But the client-facing server has no opportunity to bind its state (ech_hrr_key) into the HRR cookie. (Perhaps there isn't even one. If there is, it's encrypted with the backend server's key anyway. Either way, it's fixed now.)

The simplest solution to all this is to only support stateful client-facing servers in split mode, unless the client-facing and backend servers can coordinate enough to share one cookie. I don't know if that would satisfy everyone. I could imagine doing something horrific to HRR.cookie, akin to what we did to ServerHello.random, but that sounds really messy.

**Comment by cjpatton** [comment]
Let's mark this as an "OPEN ISSUE" in the draft.

**Comment by davidben** [comment]
> Let's mark this as an "OPEN ISSUE" in the draft.

Done. https://github.com/tlswg/draft-ietf-tls-esni/pull/338
