### ISSUE TITLE
Define separate codepoint (and name) for inner ECH extension

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#348]
It is unclear how a general TLS server is supposed to react to an ECH extension. It's sometimes empty and sometimes a ClientECH. An empty extension is not a valid ClientECH extension, so a server expending ClientECH should produce a `decode_error` (and vice versa).

The spec does talk about client-facing and backend servers as separate kinds of servers, but I thought the theory behind Split Mode was that backend servers were meant to be mostly standard TLS servers. That would suggest that backend-server-specific logic should be common to all TLS server implementations that know about ECH. In that case, perhaps we should say that:

* The client ECH extension is either empty or a ClientECH structure.
* If you see empty, this is an inner ClientHello. Do the ServerHello.random thing and otherwise handshake normally.
* If you see non-empty and have ECHConfigs, parse as a ClientECH and decode_error on parse failure as usual. Do the client-facing server thing.

Or is the idea that client-facing and backend servers are completely separate beasts and everyone always knows which they are? In that case, what happens if a client-facing server sees an empty ECH extension? What happens if a backend server sees a ClientECH-carrying ECH extension. Failure to parse an extension is normally fatal, but the two categories of server believe different parses are valid. In particular, this requires a backend server *never* see a general-purpose client connection, since it'd get confused by (possibly GREASE) ClientECH extensions.

**Comment by cjpatton** [comment]
> The spec does talk about client-facing and backend servers as separate kinds of servers, but I thought the theory behind Split Mode was that backend servers were meant to be mostly standard TLS servers. That would suggest that backend-server-specific logic should be common to all TLS server implementations that know about ECH. 

I think this is the intention, yeah. This is how I understand things:
1. Every TLS server is a backend server. If a TLS server knows a set of ECHConfigs, then it is also a client-facing server.
1. An empty ECH extension signals that the server should play the role of the backend server.
1. A non-empty ECH extension signals that the server should play the role of the client-facing server. The server ignores the extension if it is not a client-facing server.

**Comment by davidben** [comment]
Yeah, sounds like you and I are on the same page there. But I'm not sure the spec text actually supports that interpretation. Let's fix that.

**Comment by chris-wood** [comment]
Agreed. Who wants to take the PR?

**Comment by cjpatton** [comment]
I'd be happy to take it, since David did a lot of the heavy lifting last week. Unless you want to take a crack at it, David?

**Comment by cjpatton** [comment]
I'm working on a PR.

**Comment by cjpatton** [comment]
PR ready. Note that it also clarifies how the client's role (real or GREASE) is determined.

**Comment by davidben** [comment]
Another thought: we could also avoid this odd "maybe empty, maybe not" behavior by just using a different codepoint for the "please give me an ECH acceptance signal" extension. As things stand, the {{server-hrr}} text is also kinda off:

> If CH1 contains the "encrypted_client_hello" extension but CH2 does not, or if CH2 contains the "encrypted_client_hello" extension but CH1 does not, then the server MUST abort the handshake with an "illegal_parameter" alert.

That text doesn't account for CH1 containing a ClientECH "encrypted_client_hello" extension and CH2 containing an empty "encrypted_client_hello" extension. If the two modes are different codepoints, we don't have to keep expending words to talk about the two flavors.

**Comment by davidben** [comment]
The downside of two codepoints is it's now possible to construct a ClientHello with both extensions at once and we need to decide whether, on ECH reject, the client-facing server is expected to do the ServerHello.random computation, error, or ignore it. I don't care strongly there. Any of option seems fine.

Doing the computation has a nice orthogonality to it. We'd just be saying:
* There's this swizzle_server_random extension. If you see it in the ClientHello you process, go do the thing. Whatever.
* Independently, there's an encrypted_client_hello extension. If you see it, try to decrypt it and use it.
* Backend servers behind client-facing servers MUST support swizzle_server_random and the client MUST stick swizzle_server_random in ClientHelloInner. These two rules together avoid the trial decryption mess.

**Comment by cjpatton** [comment]
I'd support this change. Is there a downside to relaxing the client requirement to "MAY stick swizzle_server_random in CHI"? That would allow client implementations to bear the burden of trial decryption, if they want. (I don't think it make a difference on the server side.)

IIRC a similar idea came in the long-long ago of #287 and people didn't seem to like it. I could be wrong though.

**Comment by davidben** [comment]
What would be the point of allowing that? Having two ways to do something adds complexity to the protocol and ecosystem. (E.g. a client that does trial decrypt instead will fail to ensure backend servers implement their requirements.) We should add options in the protocol as a last resort when we really need it, not because we can.

(Elsewhere, TLS 1.2 session tickets specified two different ways to check something. We ended up with random downstream protocol picking the wrong one and a security vulnerability in OpenSSL.)

**Comment by cjpatton** [comment]
Agreed, just wanted to confirm.

**Comment by cjpatton** [comment]
@davidben, can we merge this #350 before we consider changing the codepoint of the inner ECH extension?

**Comment by davidben** [comment]
Oh sorry, missed that was waiting on me. Looking.

**Comment by chris-wood** [comment]
I landed #350. We can spin up a PR with separate codepoints now, if desired. (I also like the idea!)

**Comment by chris-wood** [comment]
@cbartle891 is going to take a stab at this!

**Comment by ekr** [comment]
I agree that this seems like the right direction. Haven't reviewed the PR.

**Comment by chris-wood** [comment]
Fixed in #360. Closing.
