### ISSUE TITLE
Avoid computing a new HPKE contexts on HRR?

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#349]
ECH currently adds an ECDH operation on *both* the first and second ClientHello. That's extra asymmetric operations, and if folks end up offloading those keys, it's two RPCs. Given that we need to bind the two decryptions together anyway, and HPKE supports multiple encrypted messages (it has an internal sequence number), perhaps it's better to just use that.

Here's a possibility: the first ClientHello makes a new HPKE context and calls context.Seal on it. The second ClientHello simply calls context.Seal on the same context, which internally increments the sequence number. Probably we copy over the first ClientHello's cipher_suite, config_id, and enc, even though they don't really do anything.

The server, if stateful, just calls context.Open to mirror the client behavior. If stateless, probably the simplest thing is to pickle the AEAD key inside the cookie. [Edit: I accidentally wrote "ticket" earlier.] It probably could also recompute the HPKE context and bump the sequence number up by one, maybe checking the selected ECHConfig and enc values didn't change. (The text already requires checking the former.)

**Comment by cjpatton** [comment]
I like this suggestion overall. A few comments:
1. It's not sufficient to store only the key in the ticket: minimally we'll need the key and the initialization vector (called "nonce" in the HPKE spec, unfortunately). We may also end up needing the exporter secret as well, although this is currently only used in ECH to compute the HRR PSK for `SetupPSKS()` and this call would go away if we decided to adopt this change.
1. In case of ECH acceptance, the backend server stores the key/IV in the ticket. This is a problem for "Split Mode": as you previously pointed out, there is currently no way for the client-facing server to convey ticket content to the backend server. Perhaps a solution to #333 is a prerequisite to this?
1. HPKE does not specify serialization of the HPKE context. This use case makes me think it should.

**Comment by davidben** [comment]
(I think you want to s/ticket/cookie/g since ticket is the resumption thing. That was my bad. I wrote ticket instead of cookie too.)

> It's not sufficient to store only the key in the ticket:

Good catch. Yes, we need to store both derived values. Although the difference between storing one short byte string or two short byte strings is largely one of semantics. (You can just as easily concatenate them and store the one resulting short byte string.) You could also store the root secret and rederive it. Whichever.

> We may also end up needing the exporter secret as well, although this is currently only used in ECH to compute the HRR PSK for SetupPSKS() and this call would go away if we decided to adopt this change.

We wouldn't need the exporter secret or SetupPSK in this design.

> In case of ECH acceptance, the backend server stores the key/IV in the ticket. [...] Perhaps a solution to #333 is a prerequisite to this?

I don't think this introduces a new problem, so there's no need to block on #333. Though we need to deal with that too. In both this design and the status quo, the client-facing server needs to either be stateful or store *something* secret in the cookie. Right now it's ech_hrr_key. In this design it's the key/IV. (Though this design introduces the alternate strategy of storing a less secret thing, where you just remember the client's public bits and recompute the HPKE context.)

> HPKE does not specify serialization of the HPKE context. This use case makes me think it should.

The serialization doesn't need to be standard or anything. A TLS server might want to keep its cookie small by observing it doesn't need the exporter secret. But some guidance might be useful, sure.

(The only thing that needs to consume the cookie is the server, who also produced it. Just as TLS doesn't (and shouldn't) specify session state serialization, yet every TLS implementation has a session state serialization. I could also implement TLS by, rather than keeping connection state in memory, write it to disk and read it back out on every packet. Even an in-memory representation is a serialization.)

**Comment by chris-wood** [comment]
This is an interesting consideration. On one hand, I agree that it's simpler to simply reuse the existing context, though on the other hand it seems to run against the general desire to use primarily CH2 for "everything." That said, ECH annoyingly requires binding between the two CHs, which we currently address by tying them together with a PSK, and this proposal is arguably simpler. 

(Anecdotally, I recall some server stacks verifying PSK binders on CH1 and then ignoring them on CH2, which was a situation that wasn't carefully analyzed in the formal analyses. I think that was fixed, though I don't recall how: are binders verified for both CHs, or only for the latter? And if verifying a binder involves a public key operation, why would ECH be any different?)

**Comment by davidben** [comment]
The "use CH2 for everything" theory mostly assumes you don't negotiate very many parameters on CH1, whereas you need to resolve ECH early to even get at CH1. And, as you note, we need to bind the two. So I think we're pretty stuck with having ECH resolved at CH1 rather than CH2 anyway.

Verifying a binder doesn't require a public key operation. It's mostly an HMAC. If you resolved the PSK at CH1, you've got the PSK available for CH2 and can compute the binder easily enough. If you resolved the PSK at CH2[*], then you just do it normally.

[*] As an aside, you only sort of are able to do this. If your stack implements psk_ke, which thankfully most folks didn't, you need to resolve PSK at CH1 to know if you need a key share at all. Whereas if you know you only support psk_dhe_ke, then you can proceed assuming you need a key share and defer sorting out the PSK to later.

**Comment by chris-wood** [comment]
> The "use CH2 for everything" theory mostly assumes you don't negotiate very many parameters on CH1, whereas you need to resolve ECH early to even get at CH1. And, as you note, we need to bind the two. So I think we're pretty stuck with having ECH resolved at CH1 rather than CH2 anyway.

Yeah, I think that's right.

> Verifying a binder doesn't require a public key operation. It's mostly an HMAC. If you resolved the PSK at CH1, you've got the PSK available for CH2 and can compute the binder easily enough. If you resolved the PSK at CH2[*], then you just do it normally.

What if the key is inside a ticket? Doesn't that require a public key operation? (I should have clarified that I was referring to the whole process, involving getting the key and then using it to verify the binder. Sorry!)

**Comment by davidben** [comment]
> What if the key is inside a ticket? Doesn't that require a public key operation? (I should have clarified that I was referring to the whole process, involving getting the key and then using it to verify the binder. Sorry!)

I guess it depends on how you do your tickets. They're typically just encrypted with a symmetric key, but I've also seen folks use asymmetric stuff. But, in any case, if you decrypt the ticket at CH1, by CH2 you've already gotten the decrypted ticket so you just compute the binder and don't redo the ticket business. If you decrypt the ticket at CH2, you only have the one ticket decryption by construction.

**Comment by davidben** [comment]
PR in #352.
