### ISSUE TITLE
Transcript hash construction

### ISSUE THREAD

**Issue by kylon94** [tlswg/draft-ietf-tls-esni#359]
I heard about Encrypted Client Hello recently. Looks like a good idea. I have been thinking about implementing and suggest a clarification in the draft.

It needs to specify which ClientHello the client should use to compute the transcript hash. I assume if the connection to the backend server is successful it should use the ClientHelloInner, Else, if it authenticates to the public name it should use the ClientHelloOuter.

Might be kind of obvious, but explicit > implicit. Maybe some text extending Section 4.4.1 of RFC8446 should be added.

**Comment by chris-wood** [comment]
Thanks, @kylon94! We'll try and clarify this.

**Comment by kylon94** [comment]
Looking at section 5.1, I think some clarification would be helpful. It makes sense that the full ClientHelloInner with the outer extensions should be included in the hash but this isn't clear. In particular highlighting the change in message length between the ClientHelloInner and EncodedClientHelloInner would help. Like the issue above, not a big deal but it could trip up a developer.

**Comment by cbartle891** [comment]
@kylon94 Why would highlighting the change in message length help with this?

**Comment by cbartle891** [comment]
Blocked on the issues discussed in https://github.com/tlswg/draft-ietf-tls-esni/issues/373.

**Comment by kylon94** [comment]
> @kylon94 Why would highlighting the change in message length help with this?

Because the ClientHello encoding process is new for ECH, a developer might use the wrong message length in the transcript hash even if they used the correct content. Being clear about using the full ClientHelloInner with outer extensions is more important, but mentioning the length too might help out some developers.

**Comment by chris-wood** [comment]
I believe this is fixed as part of #423, so closing. Please reopen if further clarifications are desired!

**Comment by kylon94** [comment]
This text is clearer now, but I don't think this has been fully resolved. In sections 6.1.5 and 6.1.6, being explicit about what is and isn't included in the transcript hash would help. Highlighting that the EncodedClientHelloInner is not used and the difference in length should prevent developers making those mistakes.
