### ISSUE TITLE
Potential SNI leak via cross-ECH resumption

### ISSUE THREAD

**Issue by kjacobs-moz** [tlswg/draft-ietf-tls-esni#369]
Martin pointed out a potential SNI leak via resumption under the following conditions:
1. A client connects to server "A" without ECH, and receives a session ticket.
2. The client later resumes the connection to server "A" using ECH. An observer can see that a PSK was accepted (via SH containing pre_shared_key). 
4. If any of the hosts previously visited by the client are known, an attacker can do a lookup of each for a config_id matching the resumed session. 

This effectively reduces the size of the anonymity set for a particular client/victim.

While it's true that the hostname is already leaked by the first connection without ECH, this seems to violate the security goals as they are written. We used to require separation between non-ECH and ECH PSKs, but it was removed in #285.

**Comment by davidben** [comment]
Ah fun. I agree that observing a resumption does increase the probability the connection was one of the previous non-ECH connections the client made, when server just deployed ECH. (Though the client could also be visiting someone else in the anonymity set for a second time.) I'm not sure I follow what's going on in (3) though. Is that just checking if one of the previously-visited hosts shares a client-facing server with the connection under attack? That seems like something the attacker can regardless. (With or without resumption, one would expect a client's visited sites pre-ECH-deployment to somewhat predict with the ones post-ECH-deployment.)

As an aside, even if SH.pre_shared_key was hidden, the observer can infer resumption based on whether the server responded with a lot of data (it sent a certificate in there), or very little data (it sent no certificate in there). Unless the server adds some truly wasteful padding on resumption connections.

**Comment by kjacobs-moz** [comment]
(3) just provides additional evidence that the SNI guess is correct (by further constraining set of possible hostnames).

**Comment by cjpatton** [comment]
To mitigate this, it ought to be sufficient to have the client track whether a given PSK was established ruing a ECH handshake or a non-ECH handshake. It seems like this would be a lot more involved for a server to manage.

**Comment by davidben** [comment]
Is it actually additional evidence? It doesn't seem to narrow the usual ECH anonymity set, just identifies it. If I understand you correctly, (3) is:

* The attacker observes a connection from the client with some config_id and some secret SNI A.
* The attacker queries DNS or the recovery flow[*] for the cleartext SNIs that the client previously visited and sees if one of them, B, has an ECHConfig with matching config_id.
* If there is a match, the attacker learns that B was in the same anonymity set as A.

The attacker learns this whether or not the connection resumes. The attacker also hasn't expanded the anonymity sent. In fact, they didn't even need to query sites the client previously visited. They could just as easily query the top N sites or a list of popular hosting providers known to support ECH. I think this information is part of the baseline for our security goals.

It is true that a client which, before ECH, leaked that it visited A many times is more likely to visit A again in the future. I think the interesting thing is that (2) tells the observer that it is *some* repeat visit, which increases the chance it's A.

I don't think PSK separation even mitigates this. Repeat post-ECH visits still reveal whether resumption happened in ServerHello. And even if we fixed that, depending on how much padding the client is willing to add, the ClientHello size will reveal whether the client had a ticket to offer. I think the only thing PSK separation mitigates is that _immediately_ after the client/server pair deploys ECH, you get to reset the repeat visit counter. But once you count to 2 again, you've got the same signal as before.

[*] Although there's no actual requirement that the recovery flow use the same ECHConfig as the long-lived DNS config...

**Comment by cbartle891** [comment]
> In fact, they didn't even need to query sites the client previously visited.

Well no, but since they have that information, they can further reduce the anonymity set. (The attacker doesn't need to consider the sites the user never visited.)

As soon as you involve non-ECH in a session, the security guarantees just don't hold. I'm fine with just being explicit about that in the draft.

**Comment by kjacobs-moz** [comment]
> > In fact, they didn't even need to query sites the client previously visited.
> 
> Well no, but since they have that information, they can further reduce the anonymity set. (The attacker doesn't need to consider the sites the user never visited.)
> 
> As soon as you involve non-ECH in a session, the security guarantees just don't hold. I'm fine with just being explicit about that in the draft.

That's probably the best way to resolve this, given the impracticality and constraints (to time of deployment or enablement). I'll have a PR up by the end of the week.

**Comment by chris-wood** [comment]
That works for me. Thanks, @kjacobs-moz!
