### ISSUE TITLE
Proposal: Introduce HelloRetryRequestOuter/Inner

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#374]
I wanted to jot this down before the holidays, in advance of writing a more rigorous PR. This is a proposal to go fix all our HRR problems in one swoop (#233, #373, #358, and #333).

First, whatever our "don't stick out" goals are (#354), sticking out on true HRR flows is pretty much hopeless if the attacker is allowed to make a second connection and probe server behavior: replay the first ClientHello and then perturb the second ClientHello's ciphertext. The server can't change its mind after the fact. So I'm going to intentionally give up on that, which means fixing #358 is possible. The proposal is thus:

* The client sends ClientHelloOuter1 and ClientHelloInner1 as in the current document.
* If client-facing server accepts ECH, it forwards ClientHelloInner1 to the backend server, as before.
* If the backend server sends HelloRetryRequest in response, call this HelloRetryRequestInner.
* The backend server constructs HelloRetryRequestOuter containing the following:
  * An encrypted_client_hello extension with the HelloRetryRequestInner, encrypted with the HPKE context (see open questions).
  * Optionally, a cookie extension with the outer cookie (fixes #333)
  * No other extensions are allowed, though future extensions, if solicited by ClientHelloOuter1 may change this. (See open questions.)
* HelloRetryRequests signals to the client whether ECH was accepted or not (fixes #373, avoids #316) by the presence of the encrypted_client_hello extension:
* If there is no encrypted_client_hello extension, the client computes ClientHello2 based on ClientHelloOuter1 and HelloRetryRequest. There is no more ClientHelloInner2. We're not doing ECH, and HRR may not even be valid for CHI2 (the #316 mess). Instead, it blindly copies over ClientHelloOuter1's extension. This is a waste of bytes, but fixes #358.
* If there is an encrypted_client_hello extension...
  * First, the client decrypts HelloRetryRequestInner. If it fails, it sends decrypt_failure and aborts. GREASE ECH is considered to always fail to decrypt and always sends decrypt_failure.
  * Otherwise, the client computes ClientHelloInner2 based on HelloRetryRequestInner in the usual way, handling errors in the usual way.
  * The client constructs ClientHelloOuter2 containing the encrypted ClientHelloInner2 and HelloRetryRequestOuter.cookie. We know the server is accepting ECH at this point, so there is no need to send much of any other fields. See open questions below.
* HRR or not, the ServerHello is required to have an ECH acceptance confirmation as usual. The client processes it as follows:
  * If there was no HRR, do what the document currently says and figure out ECH acceptance here.
  * If there was an HRR, you already know ECH accept or reject. If ECH reject, move and and complete the outer handshake without any fuss. The inner handshake terminated too early to compute handshake_secret anyway. If ECH accept, check the acceptance confirmation and send illegal_parameter or so if it's wrong. (See open questions below)

I believe this solves our various HRR problems:

* The client-facing server can send an HRR cookie without coordinating with the inner handshake (#333).
* The client does not need to evaluate one HRR against two different ClientHellos, so the two ClientHellos can have arbitrarily different preferences (#233, #316).
* The client knows ECH accept at the first server response, so it does not need to construct two different second ClientHellos (#373).
* The ECH extension only changes when solicited (#358).

Thoughts?

#### How and should we encrypt HelloRetryRequestInner?

The above sketch encrypts HRRInner, but HPKE only allows the sender to encrypt. This is easy to specify though: use the exporters to derive another AEAD key and toss it into the HPKE cipher suite's AEAD.

As for why encrypt it, things should still work if we stick it in the clear. But we may want to for two reasons:

1. Like backend server tickets, backend server cookies are, today, not particularly constrained w.r.t. what they reveal. A ticket or cookie from one TLS implementation may be different from the other, and Split Mode servers may have multiple backend implementations in their anonymity set. It may also vary for other reasons. NewSessionTicket is encrypted, as is the pre_shared_key extension, so we've solved it for tickets. ClientHello.cookie is also encrypted, which leaves HRR.cookie. Encrypting HRRInner fills that in.
2. If HRRInner is not authenticated by the HPKE context, an attacker can try to distinguish GREASE by sending a fake cleartext HRRInner and seeing how the client responds. Authenticating HRRInner means you cannot spoof an inner HRR flow.

Whether the second property is worthwhile is unclear (https://github.com/tlswg/draft-ietf-tls-esni/issues/354#issuecomment-743924431), but I think the first property is valuable, at which point we get the second anyway.

#### Other HelloRetryRequestOuter extensions? What is ClientHelloOuter2?

This design avoids #316 by assembling a cursory ClientHelloOuter2, rather than actually trying to continue the outer handshake. We would need to decide how to do that. I can think of a few possibilities:

1. Simply specify throwaway values for all the non-extension fields and declare ClientHelloOuter2 contains exactly two extensions, an optional cookie and encrypted_client_hello. EncodedClientHelloInner2 does not bother with outer_extensions because there is nothing to compress.
2. Make up a new message type to avoid the throwaway fields.
3. ~~Compute an actual ClientHelloOuter2, following RFC8446, based on ClientHelloOuter1 and HelloRetryRequestOuter. If HelloRetryRequestOuter wants to request new key_shares, that's fine. it's just pointless.~~

I don't like option 3. It's conceptually kinda clever, but adds unnecessary fuss to the protocol. Consider a client which sends CHO1.key_share == CHI1.key_share and compresses them. Key share preferences are rarely secret and this avoids doubling up potentially large post-quantum values.

The backend server now requests HRR because it wanted a different key share. So CHI2.key_share != CHI1.key_share and is based on HRRI.key_share. But the client-facing server probably did the straightforward thing and didn't send HRRO.key_share because there's no point. It'll never process CHO2.

Option 3 would then require that CHO2.key_share == CHO1.key_share because HRRO did not request a change. That means CHO2.key_share != CHI2.key_share and the client must waste a lot of bytes sending two of them. In contrast, options 1 and 2 say that CHO2.key_share doesn't exist anyway, so we only ever send one key share.

It also adds implementation complexity to the client, which now needs to evaluate two different full-featured HRRs in one handshake, despite it being unused.

Option 1 and 2 are basically equivalent, though it's worth noting that HRRO and CHO2 do not _quite_ have the same rules as anymore, so whether we want to stick them in the same message type is interesting...

#### SH.random acceptance signal after HRR?

After HRR, the SH.random acceptance signal doesn't do anything. We could just as easily omit it, because the client has already gotten the signal. The above sketch keeps it in, mostly for consistency's sake: right now we require that backend servers support the ech_is_inner extension. Getting this wrong will be noticed because the client will not successfully complete the connection. If we omit the acceptance signal in HRR flows, the client will no longer consistently notice. As long as we have this requirement, enforcing it uniformly is more robust, so I'm thinking we keep it in there.

#### Copy or omit CH2.encrypted_client_hello on reject?

This sketch says to copy CH2.encrypted_client_hello on ECH reject. This is a waste of bytes but retains compatibility with RFC8446's rules. In particular, we know of a compatibility issue in #358. It seemed from the WG discussion we generally think the RFC8446 rules are wrong, so we could intentionally break them and drop the extension.

My inclination is we should try to get the rule changed and implementations fixed, but maybe that should happen separately from ECH and we copy it for now.

**Comment by davidben** [comment]
@ekr, I'm curious what your thoughts are. I remember you said at the WG meeting you wanted to avoid #316 in the final design.

**Comment by cjpatton** [comment]
I'll need to stew on this for a bit, but I support this idea overall. One request: It seems like some design decisions are aimed at reducing the communication overhead compared to ECH-09. For now, I would prefer we leave out of t he PR any such optimization that adds implementation complexity. In particular, I think the client should compute a real ClientHelloOuter2 as usual (as in option (3.) above) rather than do something different (as in option (1.) or (2.)). The alternatives seem somewhat invasive; and if their only benefit is improved communication overhead, then given how rare the HRR code path is in practice, I don't think it's worth doing.

Also, I'm sold on the privacy benefits of encrypting HRRInner. However, I think we should punt this to a future PR. Two reasons. First, I think this privacy consideration is orthogonal to the issue at hand. Second, the details aren't straight-forward; we'll have to agree on how to pick the nonce, associated data, how to pad, and so on. I think we'll do ourselves a big favor by untangling these things :)

**Comment by davidben** [comment]
The issue with option 3 isn't just communication overhead. It's also implementation cost in mocking out an outer handshake on the client, even though we already know that it will be ignored. Either of options 1 or 2 would be *dramatically* simpler to implement and carry lower risk of mishaps from the complexity.

**Comment by davidben** [comment]
I've updated the description in the PR to make this clearer. The only benefit of option 3 is as a conceptual reference. As an actual protocol, it's a non-starter.

**Comment by cbartle891** [comment]
> After HRR, the SH.random acceptance signal doesn't do anything. We could just as easily omit it, because the client has already gotten the signal.

I don't really understand this. Sure, the client gets the signal that the backend server sent the HRR, but without SH.random, how can the client be sure the client-facing server didn't send the SH? The handshake will ultimately fail because the transcripts won't match, but not until then. Isn't it better if the client is able to terminate immediately after receiving the SH?

> The backend server now requests HRR because it wanted a different key share. So CHI2.key_share != CHI1.key_share and is based on HRRI.key_share. But the client-facing server probably did the straightforward thing and didn't send HRRO.key_share because there's no point. It'll never process CHO2.

Wait why would the client-facing server send anything at all in this case? Doesn't the backend server send the HRR to the client without (ideally) any modification from the client-facing server?

**Comment by davidben** [comment]
>> After HRR, the SH.random acceptance signal doesn't do anything. We could just as easily omit it, because the client has already gotten the signal.
>
> I don't really understand this. Sure, the client gets the signal that the backend server sent the HRR, but without SH.random, how can the client be sure the client-facing server didn't send the SH? The handshake will ultimately fail because the transcripts won't match, but not until then. Isn't it better if the client is able to terminate immediately after receiving the SH?

Do you mean a malicious or well-behaved client-facing server? A well-behaved client-facing server doesn't get to change its mind about whether ECH was accepted partway through. If we've got an HRR from the backend server, the SH will be from the backend server too.

If it's a malicious client-facing server, yeah, we're relying on how TLS defends against network attackers, including how it uses the transcript. But that's true of TLS in general. If we're worried about when the client notices, the transcript figures into handshake encryption, CertificateVerify, and Finished, which are all in the same flight as ServerHello. (Plus the SH.random signal is all of 8 bytes, so it's not especially cryptographically significant.)

(I also don't think we should omit it. Just observing that we could.)

>> The backend server now requests HRR because it wanted a different key share. So CHI2.key_share != CHI1.key_share and is based on HRRI.key_share. But the client-facing server probably did the straightforward thing and didn't send HRRO.key_share because there's no point. It'll never process CHO2.
>
> Wait why would the client-facing server send anything at all in this case? Doesn't the backend server send the HRR to the client without (ideally) any modification from the client-facing server?

Right. I'm saying I don't like option 3 because it _allows_ the client-facing server to send HRROuter.key_share. That means the client must have code to handle it. And then we need to reason about how this mess interacts with not wanting to waste bytes in the second ClientHello sending two key shares. And, despite all that complexity, the client-facing server doesn't actually care, so we made everything a mess for nothing.

Thus, option 3 is a useful conceptual reference, but I don't think we should actaully do it.

**Comment by cbartle891** [comment]
> If we're worried about when the client notices, the transcript figures into handshake encryption, CertificateVerify, and Finished, which are all in the same flight as ServerHello. (Plus the SH.random signal is all of 8 bytes, so it's not especially cryptographically significant.)

> (But I don't think we should omit it anyway. Just observing that we could.)

Ok, cool.

> I'm saying I don't like option 3 because it allows the client-facing server to send HRROuter.key_share. That means the client must have code to handle it.

**Comment by cbartle891** [comment]
This sounds good to me then. I'm sold on encrypting the HRRInner to prevent cookie fingerprinting.

**Comment by cjpatton** [comment]
I'm sold as well. I'd say this issue is ready for text.

**Comment by chris-wood** [comment]
@davidben, when do you think you can get to a PR for this?
