### ISSUE TITLE
Consider a shorter config ID length

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#379]
Assuming #376 lands, we need to decide how long we want this server-chosen identifier to be. There are various operational and privacy considerations at play. For example, shorter identifiers mean that GREASE clients may produce colliding values with higher probability, and the cost of trial decryption on the server may be an overly expensive operational cost for some deployments. Longer identifiers may also mean that using keys as a tracking vector is easier. (But as @ekr has pointed out, ECH does not assume DNS answer integrity, so there are other tracking mechanisms at play.) Let's use this issue to sort out this question. 

cc @davidben, @cjpatton, @martinthomson

**Comment by davidben** [comment]
(This may just be me misinterpreting what you wrote.) Why would a GREASE/real ID collision be expensive operationally? I could see being concerned about perf costs (the connection needs 1 HPKE op instead of 0), but I'm not sure I see the operational concern.

**Comment by chris-wood** [comment]
> Why would a GREASE/real ID collision be expensive operationally? 

If GREASE collides with a real key ID, then the server attempts decryption to only see that it fails, and then falls back. (The chances of that collision happening are pretty high with a 1-byte ID.) So, yeah, "expensive operationally" is "1 HPKE operation instead of 0." Whether or not that's an issue seems server-specific.

**Comment by davidben** [comment]
Ah, okay. I interpreted "expensive operationally" to mean there was some operational challenge, but you just mean it might not perform well in some deployments.

**Comment by davidben** [comment]
Although, presumably no less well than connections that actually enable ECH.

**Comment by martinthomson** [comment]
From my perspective, I am totally comfortable with a 1/64 (approximately) chance of hitting that 1 bogus HPKE operation.  A server that offers ECH has to be prepared for every connection it receives to use ECH.

But I don't operate a server, so take that position with that in mind.

**Comment by chris-wood** [comment]
> From my perspective, I am totally comfortable with a 1/64 (approximately) chance of hitting that 1 bogus HPKE operation.  A server that offers ECH has to be prepared for every connection it receives to use ECH.

Likewise. I see little reason for anything longer than a byte here.

**Comment by cjpatton** [comment]
I also am not worried about a non-negligible probability of a greased config_id colliding with a real config_Id. I think a more important consideration that came up in #376 is dealing with two real configs having the same config_id. In particular, I think the spec should make it easy for servers to avoid collisions altogether. That way the server doesn't have to resort to trial decryption in case of a collision.

At the same time, we need to make it easy for clients to grease. As has been suggested, if we want a 1-byte config_id, I think we should mandate the config_id be chosen at random, but permit rejection sampling in order to allow the server to avoid collisions. This seems link a funky requirement to put in a spec, but seems fine from a technical perspective.

**Comment by chris-wood** [comment]
I'd be fine with that as the RECOMMENDED way to generate these identifiers. Perhaps the text could say something like the following?

```
The RECOMMENDED technique for generating a new ECHConfig.config_id is to choose a random byte. This process should be repeated if this config_id matches that of any existing and valid ECHConfig.
```

Of course, clients can't validate that servers do this, so the best we can do is recommend some best practice here.

**Comment by martinthomson** [comment]
That seems like a reasonable outcome.  It require coordination, but at a level at which I think is reasonable (you don't want independent processes feeding ECH keys into the system, that is a recipe for failure).

**Comment by cjpatton** [comment]
Works for me!

**Comment by enygren** [comment]
Can we use an arbitrary length, up to some length, but with a recommendation to use one byte where possible?  There are a number of deployment environments where it may be preferable to use longer config_ids (eg, using a 8-byte config_id would allow for using a hash of a public key as the config_id without needing to do trial-decryption or demuxing).  Server operators who want to abuse this could just not enable ECH or could use a large number of IP addresses.

**Comment by chris-wood** [comment]
Discussed in 110: Poll suggested most folks were in favor of 1 byte.
