### ISSUE TITLE
Add some more structure to "Offering ECH"

### ISSUE THREAD

**Issue by sayrer** [tlswg/draft-ietf-tls-esni#395]
I think a brief summary at the top of the section might help a lot. It could just be a list with links to subsections containing the text that's already there.

As an example, I wrote this brief summary for Rustls collaborators.

```
The client steps are as follows:

- Create a ClientHelloInner (just a ClientHello with some restrictions)
- Create an “EncodedClientHelloInner” that can be a no-op for now, since we won’t deduplicate anything in the ClientHelloOuter for now.
- Create a ClientHelloOuter for the EncodedClientHelloInner (a ClientHello with some other restrictions).
- The ClientHelloOuterAAD is computed to created “Additional authenticated data” for HPKE by serializing the entire ClientHelloOuter less the last extension (which is ECH)
- The encrypted_client_hello extension (ECH) is computed using choices from the ECHConfig (done for -09) and the ClientHelloOuterAAD.
```

**Comment by cjpatton** [comment]
I like this idea. Send a PR?

**Comment by chris-wood** [comment]
@sayrer I think this has been overcome by events with the latest structure of the Offering ECH section. We now describe the steps that clients follow in linear fashion. I'm going to close this as having been overcome by events.
