### ISSUE TITLE
Hard to imagine ECH handling in constant time - ponder and document?

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#400]
Given all the complexity and options it's hard to imaging ECH handling ever being contstant-time. It'd probably be no harm to ponder that at least and maybe add some security considerations text before we're done.

**Comment by chris-wood** [comment]
That seems like a fine thing to note in the security considerations. @sftcd, will you have cycles to prepare a PR?

**Comment by cjpatton** [comment]
As long as the runtime doesn't depend on secrets, I don't see that this is an issue. I wonder, is constant-time handshaking (modulo secrets) a security consideration for TLS?

**Comment by davidben** [comment]
Well, I think the question is what do you want to protect in under the constant-time threat model. Certainly it'd be a disaster if ECH caused us to leak some values that TLS *already* considered secret. We also shouldn't leak any cryptographic secrets like the ECH keys.

At the same time, the goal of ECH *is* to hide sensitive fields in the ClientHello, and we're definitely not meeting the constant-time threat model for those fields. I don't think this has anything to do with the complexity though. It just seems mostly implausible in the first place. It'd require you pick and handshake as your selected backend server, in time and memory access patterns independent of which backend server you chose.

**Comment by chris-wood** [comment]
It's entirely possible for the runtime to vary based on the contents of the inner CH. Different domains may have different configurations (ciphersuites, signature algorithms, etc), and any variance caused by those may leak information. (This doesn't seem different from the fact that different configurations might also have on-the-wire differences [absent padding], so I'm comfortable just noting it.)

**Comment by davidben** [comment]
Yup, exactly. I don't think meeting the constant-time threat model is plausible here.

**Comment by sftcd** [comment]
On 23/03/2021 19:47, Christopher Wood wrote:
> It's entirely possible for the runtime to vary based on the contents
> of the inner CH. Different domains may have different configurations
> (ciphersuites, signature algorithms, etc), and any variance caused by
> those may leak information. (This doesn't seem different from the
> fact that different configurations might also have on-the-wire
> differences [absent padding], so I'm comfortable just noting it.)

Yeah, I think that's the best we may be able to do.

Timing will almost certainy reveal whether we're dealing
with a shared or split mode case so that likely deserves
to be noted.

However, I think it'd be worth thinking a little about
whether timing could fingerprint a set of inner CH choices,
and whether that in turn could reveal e.g. inner.SNI in
some cases, if the inner CH for very few names used some
rare combination of choices.

People do seem to get rather smart about such things over
time;-)

Cheers,
S.
