### ISSUE TITLE
ECH complexity

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#401]
Overall, having implemented and gotten interop for draft-09, ECH is very complex. This issue just requests people consider whether or not there are ways to simplify ECH given the TLS WG plan to have a bunch of interim meetings on the topic. I'd hope that now we have 3 or 4 implementations it might be possible to see ways to make 'em usefully simpler, if that's possible.

**Comment by chris-wood** [comment]
Thanks for flagging! I'm tagging this as something to keep open up and top of mind as we progress towards something shippable. When all other issues are resolved and we can't figure out how to make things simpler, it's probably time to close this.

**Comment by chris-wood** [comment]
Closing per discussion at IETF 118.
