### ISSUE TITLE
Not all of CHOuter is authenticated

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-esni#402]
The position of the ECH extension is not authenticated as part of ClientHelloOuterAAD.  This means that it is possible to construct multiple different ClientHello messages that will all be accepted.

This probably isn't that interesting, but it might be worth noting.

**Comment by davidben** [comment]
If we want to fix this (don't care either way), we can remove the fields prepended to ClientHelloOuterAAD, put the ECH extension back in, and say the AAD is computed by replacing ClientECH.payload with the empty string.

**Comment by chris-wood** [comment]
That seems like a reasonable proposal. @martinthomson, what do you think? (@sftcd might also have thoughts on this, one way or the other.)

**Comment by martinthomson** [comment]
I can live with either a placeholder or text in the draft that explains the limitation.  Extension order doesn't carry any semantics, so I don't see malleability as a real risk.  I'd lean toward the placeholder, but only slightly.  More so if we were planning to change the AAD anyway.

**Comment by cjpatton** [comment]
This seems like a good idea to me.

**Comment by davidben** [comment]
I guess it exposes an active distinguishing attack, though I suspect this style of attack has plenty of vectors:

* Attacker rewrites CH to move the ECH extension to another spot and forwards to server
* Server responds with SH..Finished. Attacker forwards that to client unmodified
* If this was negotiating CHOuter, this would break the transcript and the client would reject. If this was negotiating CHInner, the client won't notice and proceed

**Comment by chris-wood** [comment]
Yep, nice! Let's definitely make this change, then.
