### ISSUE TITLE
public_name and maximum_name_length could be smaller

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-esni#403]
I think that we're committed now to public_name being a DNS name (there is no way to indicate the type of name (like in RFC 6066).  So I have to assume that the only type of name that is permitted is a DNS name.  And a DNS name can't be longer the 255 bytes.

Therefore, ECHConfig could be:

```tls
    struct {
        HpkeKeyConfig key_config;
        uint8 maximum_name_length;
        opaque public_name<1..255>;
        Extension extensions<0..2^16-1>;
    } ECHConfigContents;
```

**Comment by cjpatton** [comment]
This seems like a sensible change.

**Comment by cbartle891** [comment]
Why is there is no way to indicate the type of name?

**Comment by cbartle891** [comment]
I wasn't referring to anything other than Martin's comment, but that comment answers my question (modulo the whole underscore business, which isn't officially documented anywhere).

**Comment by davidben** [comment]
Re the BoringSSL comment, we sent this mail to the TLSWG way back:
https://mailarchive.ietf.org/arch/msg/tls/1t79gzNItZd71DwwoaqcQQ_4Yxc/
