### ISSUE TITLE
[Question] Is there any public-facing setups that currently support ECH?

### ISSUE THREAD

**Issue by cujof** [tlswg/draft-ietf-tls-esni#404]
Hello. Thank you for your work on ESNI/ECH.

With ECH gaining momentum, are there any public functional sites that publish `echconfig` via DNS and able to perform TLS handshake with ECH? I see Firefox already adding ECH support, but I haven't found any site where I can do testing. Please share this information (if there are any).

**Comment by TheDGOfficial** [comment]
Only Cloudflare and Firefox currently, however, they use old draft version
as far as I know.

You can check it from these sites:

https://www.cloudflare.com/ssl/encrypted-sni/

https://esnicheck.com/

It will be implemented on all major web browsers and servers once the draft
is finalized I think.

**Comment by cujof** [comment]
Thanks for quick reply! Well, encrypted SNI (ESNI, older drafts) is very different from ECH (current). That old Cloudflare ESNI checker based on DNS `_esni.*` TXT records. That concept was abandoned in favor of encrypting ClientHello using `echconfig` retrieved from DNS. But I see in TLSWG mailing list message from Stephen Farrell:

> I've just got my OpenSSL code "working" for draft-09. 
The s_client and s_server talk to one another and do 
ECH; NSS's tstclnt talks to my s_server and does ECH 
and my s_client talks to **cloudflare's test server** and 
does ECH. 

So at least Cloudflare has a testing server, would be great to know which exactly.

**Comment by sftcd** [comment]
On 23/03/2021 16:17, Filip wrote:
> So at least Cloudflare has a testing server, would be great to know which exactly.

It's crypto.cloudflare.com

I just re-tested with my s_client and that seems to
still be running draft-09. That should change to
draft-10 (a breaking change) sometime soon, but we
probably need to wait for CF to say when and if they
are going to use the same name.

Cheers,
S.

**Comment by cujof** [comment]
@sftcd, thank you very much, sir!

I think this issue is resolved.

**Comment by cujof** [comment]
@sftcd just in case you are interested in more sites for testing: take a look at HTTPS RRs of these sites:

* app-site-association.g.aaplimg.com
* clientflow.g.aaplimg.com
* pancake.g.aaplimg.com

They have key `key32768` which seems to be the replacement for `echconfig` in Apple's experiments with ECH. Google knows nothing about that key.
