### ISSUE TITLE
public_name edge cases and client checks

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#405]
Some edge cases around the public_name:

1. What if the public name is some random string which is not a valid DNS name? (What's the right terminology here? Same from RFC6066?) Does the client reject the ECHConfig? My feeling is yes. Imagine you have some random service accessible on a private address. Today, it can assume it'll never see `\"\r\n;DROP TABLES` in the server_name field. Even if an attacker pointed `evil.example` at that private address, the attacker is constrained by valid DNS strings. But the public name is never directly queried in DNS.

2. Is a server deployment allowed to use an IP certificate for the ECH rejection identity? (That was actually the original idea for the fallback flow.) If so, how do they specify it? Do they use the ASCII serialization of the IPv4 or IPv6 address? Note that IP addresses do not go in server name, so the client would need to recognize this and leave server_name empty.

@dmcardle

**Comment by chris-wood** [comment]
I imagined the outer name would be set from the config similar to how an application sets the inner name. That is, one provides a string to `set_server_name(char *)` and, internally, the library determines whether or not that string is a valid domain name (and thus goes in the server name) or is an IP address (and thus is used to verify the IP-based cert that might come back from the server). ASCII serialization of addresses seems fine here, if one just takes that string and passes it to the `set_server_name(char *)` function (or equivalent).

**Comment by davidben** [comment]
Well, OpenSSL and derivatives have a lower-level API and just take the server name as an opaque string. :-) But yeah, that seems a reasonable model.

What do you think should happen if the public name is neither a valid DNS name, nor a valid IP address? Like `\"\r\n;DROP TABLES`. ECHConfig parse error would be my inclination.

**Comment by chris-wood** [comment]
> What do you think should happen if the public name is neither a valid DNS name, nor a valid IP address? Like \"\r\n;DROP TABLES. ECHConfig parse error would be my inclination.

Yeah, that seems like a configuration error on behalf of the server.

**Comment by dmcardle** [comment]
> Today, it can assume it'll never see \"\r\n;DROP TABLES in the server_name field. Even if an attacker pointed evil.example at that private address, the attacker is constrained by valid DNS strings. But the public name is never directly queried in DNS.

That seems like it's already an unsafe assumption, right? Malicious clients could send SQL-injection strings to vulnerable servers without ECH.

I suppose ECH introduces some asymmetry; one malicious DNS server could cause N clients to send the malicious payload.

**Comment by dmcardle** [comment]
Backing up a step, if we care to protect applications from malicious/malformed DNS hostnames, it seems prudent to validate all incoming server_name values on the server, whether they came from ClientHelloInner/ClientHelloOuter or even a non-ECH ClientHello. (Assuming we're using the RFC6066 HostName definition.)

**Comment by chris-wood** [comment]
@dmcardle yeah, that's basically what I was thinking the `set_server_name()` function would do. Would you have cycles to prep a PR to resolve this issue?

**Comment by davidben** [comment]
> That seems like it's already an unsafe assumption, right? Malicious clients could send SQL-injection strings to vulnerable servers without ECH.

It depends. Services running on private networks often make a lot of assumptions. These assumptions are pretty questionable, but we put in effort to [protect them](https://wicg.github.io/private-network-access/) anyway because that is reality.

> Backing up a step, if we care to protect applications from malicious/malformed DNS hostnames, it seems prudent to validate all incoming server_name values on the server, whether they came from ClientHelloInner/ClientHelloOuter or even a non-ECH ClientHello.

Yes, any server listening on a network should tolerate arbitrary input and behave well. Nonetheless, the reality is private services are often buggy. Where we break soft assumptions that might have previously (mostly) worked, we should at least think about it. Here, it seems there's no point in breaking the assumption.

**Comment by dmcardle** [comment]
Ah, servers at private addresses was not even on my radar. I support client validation of ECHConfig.public_name at parse time AND server validation of all ClientHello* server_name extensions.

@chris-wood: Happy to do a PR.

**Comment by davidben** [comment]
(I don't think the ECH spec should say anything about server validation here. The server looks at whichever ClientHello it selects and does whatever it would normally do with the server name in the selected one.)

**Comment by cbartle891** [comment]
> What if the public name is some random string which is not a valid DNS name? (What's the right terminology here? Same from RFC6066?) 

There doesn't seem to be a standard that reflects actual current practice. Chrome and Firefox accept SNIs with underscores, which are not allowed in valid DNS names (https://bugs.chromium.org/p/chromium/issues/detail?id=463410).

**Comment by dmcardle** [comment]
Yep, thanks for raising that, Carrick. Perhaps we should make hostname validation a SHOULD rather than MUST?

**Comment by cbartle891** [comment]
The issue doesn't sound like a MUST vs. a SHOULD but rather what they SHOULD or MUST do. I guess we could say "do whatever you usually do with the SNI."

**Comment by cbartle891** [comment]
Oh and yeah, SHOULD seems like a better idea than MUST since there are conflicting opinions about the right way to go about it.

**Comment by davidben** [comment]
It's a little tricky due to what layers we're talking about. Chrome doesn't particularly validate the SNI at the TLS level. Rather, we leave that to URL parsing and DNS logic earlier in the pipeline. If we've gotten far enough to make a TLS connection, we assume we're happy with the string we're passing to SNI and certificate validation. I imagine this is reasonably common: OpenSSL likewise treats the set_server_name API as an opaque byte string.

ECH breaks this assumption by bypassing all the earlier layers. Suddenly a TLS-level construct (ECHConfig) is fabricating a DNS name on its own, and now TLS needs to pick up all the validation.

**Comment by cbartle891** [comment]
Technically couldn't DNS logic validate the DNS name in the ECHConfig?

**Comment by dmcardle** [comment]
Hi folks, PR #413 is a little more complete now, if you could you get a chance :)

**Comment by davidben** [comment]
> Technically couldn't DNS logic validate the DNS name in the ECHConfig?

To close the loop on this: it could, but we're treating the ECH parts of SVCB as opaque to TLS. I think that's desirable because TLS may introduce new ECH extensions or ECH versions that the DNS stack may not be aware of. Also, any validation on the URL parsing / DNS query path happens in the process of making a request to the DNS server at all, whereas any validation here would be a check afterwards on the result. Whatever we do, it'll end up looking like someone, DNS or TLS, implementing a check we need to write down.

**Comment by bemasc** [comment]
> 2\. Is a server deployment allowed to use an IP certificate for the ECH rejection identity? (That was actually the original idea for the fallback flow.) If so, how do they specify it? Do they use the ASCII serialization of the IPv4 or IPv6 address? Note that IP addresses do not go in server name, so the client would need to recognize this and leave server_name empty.

To come back to this: because SNI does not support IP addresses, IP certs must be the server's default-cert, i.e. they must be served to requests that omit the SNI.  Thus, we merely need a way to tell clients to omit `ClientHelloOuter.server_name`.

My suggestion is to allow `ECHConfigContents.public_name` to be empty, meaning "omit outer SNI".

**Comment by dmcardle** [comment]
Keeping in mind that the client uses `public_name` to authenticate the server's `retry_configs`, the client now needs to be aware of which IP address it's connecting to. I suppose this isn't a protocol concern, but it's more ergonomic when the ECHConfig contains all the information TLS needs to do ECH.

**Comment by bemasc** [comment]
OK.  As I mentioned yesterday, I think `public_name` should probably be an X.509 [`GeneralName`](https://tools.ietf.org/html/rfc5280#section-4.2.1.6).

**Comment by davidben** [comment]
I do not think GeneralName will work. There's somewhat a mismatch between what the application thinks of as identities and how those identities are encoded into X.509. GeneralName is part of the latter. What does a browser certificate verifier, which only believes in things that fit in a URL, do if it's told the identity is now an EDIPartyName? What SNI, etc., does that translate into, given that our identity-to-TLS-config algorithm takes an origin, not an X.509 name? (Note that the type field in SNI is fiction. There is and will be [only one name type](https://mailarchive.ietf.org/arch/msg/tls/1t79gzNItZd71DwwoaqcQQ_4Yxc/).)

More importantly, this glomming too many things into an already overloaded issue. If you want to pursue this, can you please fork GeneralName into a separate topic? The status quo is that the public name is clearly only good for DNS or DNS+IP, depending on how much you believe in URL syntax. We already have a need to better specify that case, including client validation. Let's fix that, and then we can separate tackle more complex cases.

**Comment by sftcd** [comment]
On 02/04/2021 16:32, Benjamin M. Schwartz wrote:
> OK.  As I mentioned yesterday, I think `public_name` should probably
> be an X.509
> [`GeneralName`](https://tools.ietf.org/html/rfc5280#section-4.2.1.6).

Strongly disagree. GeneralName was a reasonable guess at a
thing to do 20 years ago but is no longer a structure that
ought be leveraged - we have no need for EDI nor X.400 names
for ECH and even tempting someone to write code for ORAddress
handling is risky - there's >1 can of worms there all of
which are best avoided.

S.

**Comment by richsalz** [comment]
Agree with Stephen. Using GeneralName is like hunting butterflies with an elephant gun. :)

**Comment by chris-wood** [comment]
Addressed in #456, closing.
