### ISSUE TITLE
Make it easy to reference EncodedClientHelloInner decoding concerns

### ISSUE THREAD

**Issue by sayrer** [tlswg/draft-ietf-tls-esni#430]
https://tools.ietf.org/id/draft-ietf-tls-esni-10.html#section-5.1-9

This should have its own section or sub-section. The projects I work on generally refer to RFC sections at the most, so as not to repeat the text of the or RFC or I-D (which may grow out of date).

**Comment by chris-wood** [comment]
This section [now exists](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#name-clienthelloinner-packet-amp)! Closing as a result.
