### ISSUE TITLE
Should psk_key_exchange_modes also be omitted from ClientHelloOuter?

### ISSUE THREAD

**Issue by sayrer** [tlswg/draft-ietf-tls-esni#431]
I don't know the answer to this question, but, from the TLS 1.3 RFC:

```
   -  "pre_shared_key" is REQUIRED for PSK key agreement.

   -  "psk_key_exchange_modes" is REQUIRED for PSK key agreement.
```

I noticed this while testing with a pre-baked ClientHello that had both extensions. The ECH draft clearly required that the `pre_shared_key` extension be removed, but I wondered about `psk_key_exchange_modes`.

**Comment by davidben** [comment]
Given https://github.com/tlswg/draft-ietf-tls-esni/issues/408, https://github.com/tlswg/draft-ietf-tls-esni/pull/414, and https://github.com/tlswg/draft-ietf-tls-esni/pull/415, I'd say quite the opposite.

**Comment by sayrer** [comment]
Ah, I see text has been added saying it must appear in the ClientHelloOuter. Thanks for the references. I was working from draft-10.
