### ISSUE TITLE
Embedded ClientHello padding complicates whole-input padding schemes

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#433]
Filing this as a topic for discussion. I think "we don't like these padding strategies" or "that's not too complicated" are perfectly plausible answers.

So, we need to pad the ECH payload to avoid revealing information via length. It seems to me there are two plausible strategies for padding, and you could do one or both of them. (You could do both by applying the first, then applying the second.)

_NB: I don't know what the overall consensus is on padding strategies. My assumption has been that there isn't one and we're building flexibility into protocols so we can figure it out. The below is a summary of my current thinking, but there are probably lots of well-established ideas I don't know._ 

**Pad particular fields you are trying to hide**
There may be a particular field in your message with a length distribution you would like to hide. Perhaps some anonymity set has server name lengths up to 96 bytes. So you arrange for the client to know this, and the client adds 96 - len(server_name) extra bytes to the ClientHello somewhere. This is easy to reason about in isolation, but only considers individual fields. Information about other fields still leaks.

**Generically reduce the range of possible lengths**
You may also just try to generically reduce the range of the function. Maybe you round to a multiple of 32, or round to the next power of some R > 1. This may still leak information: padding a multiple of 32 still distinguishes (big server name, big ALPN list) and (small server name, small ALPN list) when the variance is more than 32 bytes. But it pretty uniformly reduces the information leaked in general, which can help increase anonymity sets. For example, an HTTP client will always sends an ALPN of {h2, http/1.1}, but a tiny amount of overall padding can help combine HTTP ClientHellos with a non-HTTP client that might have a slightly different ALPN set. It can also mitigate mistakes. For instance, TLS tickets often embed the server name. If the server forgets to pad that when minting the ticket, the first strategy alone will leak this.

The recommended padding scheme currently only does the first kind. We add padding for server_name and largely ignore the other fields. Suppose some client wanted to additionally use the second strategy. The order of operations here is fussy and interleaves bits of ClientHelloInner and EncodedClientHelloInner:

* EncodedClientHelloInner has a PSK binder
* ...which depends on the non-PSK extensions of ClientHelloInner
* ...which includes the padding extension
* ...which depends on the length of the non-padding extensions of EncodedClientHelloInner
* ...which depends on the length of the PSK binder, the non-PSK non-padding extensions of ClientHelloInner, which of them will be compressed

This is not actually a circular dependency. But it's a place the ClientHelloInner and EncodedClientHelloInner are awkward linked together. Probably the way to do it is to maintain a count of how much smaller EncodedClientHelloInner will be and subtract that from the ClientHelloInner as you construct and pad it.

*If* we think this is a problem, the fix is pretty straightforward: add padding to EncodedClientHelloInner itself. Something like:

```
struct {
  ClientHello client_hello;
  opaque padding<0..2^16-1>;
} EncodedClientHelloInner;
```

Now the ClientHelloInner no longer depends on the length of the EncodedClientHelloInner. Is this worth doing?

**Comment by davidben** [comment]
Forgot to mention: Another reason to round the overall payload is that GREASE will likely be much more effective if the space of common lengths is dense.

**Comment by chris-wood** [comment]
@davidben thanks for filing! This seems reasonable, and probably avoids future one-off padding changes when we discover certain extensions are sensitive to their length. I suppose one could also include the padding extension on ClientHelloInner, but that becomes weird when you consider the ticket/binder example you raise. In general, the current draft text here does seem to be an artifact of the pre-ECH padding story. Since we're now covering multiple things in the ClientHello, applying padding more broadly seems right. I think it boils down to where we put those bits. (Your suggestion seems perfectly fine, and shouldn't be too onerous to implement. It should work fairly nicely with [our current implementation](https://github.com/cloudflare/go/blob/71ba4a16b1db8a2b5f2b0f857142fc1938134a1e/src/crypto/tls/ech.go#L464).)

@cjpatton, what do you think?

**Comment by sftcd** [comment]
I need to catch up on this discussion, but FWIW, I wrote up
some notes on the padding I've done so far at [1]. I'll be
fine with changing that later if/as better ideas emerge, so
am not that invested in it as of now but it might be useful
as an input here.

Cheers,
S.

[1] 
https://github.com/sftcd/openssl/blob/ECH_UPFRONT_DEC/esnistuff/padding-notes.md

**Comment by cjpatton** [comment]
+1, this seems like a good idea to me.

**Comment by davidben** [comment]
Wrote up some text for this https://github.com/tlswg/draft-ietf-tls-esni/pull/443.
