### ISSUE TITLE
Example unsupported mandatory Configuration Extension

### ISSUE THREAD

**Issue by sayrer** [tlswg/draft-ietf-tls-esni#437]
From the section on ECH configuration extensions: "Clients MUST parse the extension list and check for unsupported mandatory extensions. If an unsupported mandatory extension is present, clients MUST ignore the ECHConfig."

Is there an always-invalid extension specified for testing? This section references RFC8446, so maybe I'm missing something in that RFC.

**Comment by sayrer** [comment]
I am not sure this is purely editorial, although it's not very technically interesting. Should there be an IANA reservation for it?

**Comment by davidben** [comment]
I also filed #451 which covers reserving some always-invalid extensions.

**Comment by sayrer** [comment]
OK, let's just go with #451.
