### ISSUE TITLE
Make the definition of key protocol elements easier to find

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-esni#454]
It took me AGES just now to find where ech_outer_extensions was defined.

The table of contents should be useful for finding important things like what to do (the current structure works OK for this, though it might be better) and to learn what the format and semantics of protocol elements is.

A careful reorganization of content is probably well overdue.

**Comment by chris-wood** [comment]
@martinthomson the document underwent significant refactoring for linear flow with references for improved readability. I'm going to close this issue with the understanding that if there are still significant editorial changes we think need to be made, they can be surfaced during WGLC (and fixed as part of processing that WGLC feedback).
