### ISSUE TITLE
Changes for draft-12 (was "Value of ECHConfig.version in draft-11?")

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#463]
ECHConfig is defined as

> ```
>       struct {
>           uint16 version;
>           uint16 length;
>           select (ECHConfig.version) {
>             case 0xfe0a: ECHConfigContents contents;
>           }
>       } ECHConfig;
> ```

but the text below it says

>   Beginning with draft-08, the version is the same as the code point
>    for the "encrypted_client_hello" extension.  Clients MUST ignore
>    any "ECHConfig" structure with a version they do not support.

The intention was to bump ECHConfig.version from 0xfe0a to 0xfe0b for draft-11, but this got missed by https://github.com/tlswg/draft-ietf-tls-esni/pull/458. (I wrote the PR, so I apologize for my part in missing this.) How do folks think we should resolve this? Do we need to cut a new draft with the ambiguity fixed?

**Comment by davidben** [comment]
Oh whoops, nice catch! Using `0xfe0a` definitely won't work since the format and corresponding ClientECH extension has changed. I suppose all the implementors could just agree to mentally fix this typo when reading the draft, but may as well cut draft-12. Draft numbers are cheap.

**Comment by cjpatton** [comment]
We could try to pick up some editorial changes, too, like those suggested in #454.

**Comment by davidben** [comment]
I'd also personally be pretty happy to have #443 in there, but also fine to skip it for what's supposed to be a small bugfix draft snapshot.

**Comment by sftcd** [comment]
On 22/06/2021 20:43, David Benjamin wrote:
> Oh whoops, nice catch! Using `0xfe0a` definitely won't work since the
> format and corresponding ClientECH extension has changed. I suppose
> all the implementors could just agree to mentally fix this typo when
> reading the draft, but may as well cut draft-12. Draft numbers are
> cheap.

+1

I've not checked recent editorial changes but they're
probably fine too.

S

>

**Comment by cjpatton** [comment]
I'd be happy to take #443 in draft-12 as well, though I'm inclined to thing this should strictly be a bugfix/editorial draft. I'd say let's wait until Chris W. gets off back from PTO and let him make the call. Unless we're in a hurry, in which case we could ping one of the other authors to merge our changes and cut a draft.

**Comment by chris-wood** [comment]
Closing as resolved.
