### ISSUE TITLE
Improve guidance for Second ClientHello construction in the event of HRR

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#515]
This was PR #497 but we're punting on that for now.

**Comment by chris-wood** [comment]
The document has been significantly improved to add more guidance around how HRR is processed, specifically in [Section 6.1.5](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#name-handshaking-with-clienthell). @sftcd, please reopen if you feel this guidance is inadequate (and ideally clarify how it's inadequate so we can craft a PR to fix!).
