### ISSUE TITLE
Question on Section 10.2

### ISSUE THREAD

**Issue by kylon94** [tlswg/draft-ietf-tls-esni#517]
Section 10.2 of the draft suggests the use of DoH/DPRIVE when querying for the ECH record to protect against attacks on the local network. Should ECH be used for this DoH/DPRIVE query too? 

Some guidance on whether or not to use it would be helpful for developers. For example covering how the ECH key should be provisioned if it is used.

**Comment by chris-wood** [comment]
Since this is specific to how ECH is bootstrapped, I suggest filing an issue to discuss this on the related [DNS bootstrapping](https://github.com/tlswg/draft-ietf-tls-svcb-ech) draft.
