### ISSUE TITLE
Anonymity set definition should include behavior

### ISSUE THREAD

**Issue by klinvill** [tlswg/draft-ietf-tls-esni#519]
The current version of the spec mentions that: 

> Co-located servers with consistent externally visible TLS configurations, including supported versions and cipher suites, form an anonymity set.

Yet decisions a server makes during the handshake (such as which cipher suite it selects from a proposed list) can also be used to distinguish connection establishment to one server from another.  In the most extreme case, this would result in anonymity sets being restricted to servers using the same TLS implementation and configuration. I'm not sure where text describing this should go (maybe a section on anonymity set considerations? maybe just update the definition to read "Co-located servers with consistent externally visible TLS configurations, [...], and behavior...") but I think it's worth a mention in the spec.

**Comment by chris-wood** [comment]
The intent of "TLS configuration" was to capture everything from algorithm choice to server behavior, but it doesn't hurt to additionally note behavior.
