### ISSUE TITLE
Expiration

### ISSUE THREAD

**Issue by JonSnowWhite** [tlswg/draft-ietf-tls-esni#538]
The official draft expired today. Is there a version bump planned?

**Comment by taoso** [comment]
Expired 😢

**Comment by letrhee** [comment]
I remember seeing a video about submitting a paper to CCS at IETF-113.
Perhaps there will be document changes after the CCS2022 decisions on submitted papers?

**Comment by chris-wood** [comment]
Since an expired draft can still be referenced, we'll update the draft when there are non-trivial changes to land. As of now, there are no changes staged.
