### ISSUE TITLE
Status of this draft?

### ISSUE THREAD

**Issue by kovalensky** [tlswg/draft-ietf-tls-esni#540]
The last update was in February and IETF draft is expired, what happened?

**Comment by chris-wood** [comment]
There have been no changes that warranted an update. The draft will be resurrected when changes land.

**Comment by richsalz** [comment]
It is not uncommon to post a new version, a refresh, just to keep things from falling out of sight. Expired drafts do not show up in the datatracker "active documents" list, for example.

**Comment by martinthomson** [comment]
While a refresh is permitted and commonplace, this is a great example of why I think that the expiration system isn't helpful.  Please don't refresh the draft until there is a reason, other than inane rules.

**Comment by chris-wood** [comment]
I had an outstanding PR to update some security considerations with a paper citation, and that seemed worthy of a new version.
