### ISSUE TITLE
Use Session ID in Client Hello to transfer enctypred SNI

### ISSUE THREAD

**Issue by 0x391F** [tlswg/draft-ietf-tls-esni#541]
Is it possible to use Session ID in Client Hello to transfer enctypred SNI? If it looks random enough, attacker could't distinguish Session ID is encrypted SNI or not. 

By the way, how to join the mailing list?

**Comment by 0x391F** [comment]
It may have some restrictions, for example, the SNI maybe couldn't longer than Session ID (32 bytes).

**Comment by chris-wood** [comment]
Hi @0x391F -- you may join the mailing list [here](https://www.ietf.org/mailman/listinfo/tls). I recommend you propose your idea there for further discussion.
