### ISSUE TITLE
My first PR - did I do it correctly?

### ISSUE THREAD

**Issue by taddhar** [tlswg/draft-ietf-tls-esni#580]
Ok thanks to answers on #578 I did my best to follow the instructions to create my first fork and as a result I did a first PR #579. 

Please anyone keep educating me as these are my first steps. 

For example should I have done my own branch on my own fork or updating my own main branch in my own fork is good enough?

Apart from that the PR itself is really a minor edit. I hope this helps a tiny bit and more to come.

**Comment by chris-wood** [comment]
The process you followed for #579 is correct! Fork, create a branch, submit a PR. That's all there is to it.
