### ISSUE TITLE
Can a retry ECHConfig change the public name?

### ISSUE THREAD

**Issue by ekr** [tlswg/draft-ietf-tls-esni#608]
Suppose that I connect to a server with public name `example.com` and it gives me an ECHConfig with public name `example.org`. Is this OK?

**Comment by sftcd** [comment]
On 25/02/2024 21:44, Eric Rescorla wrote:
> Suppose that I connect to a server with public name `example.com` and
> it gives me an ECHConfig with public name `example.org`. Is this OK?

If the same server certificate covers both, then I'd say
that's ok. But I'd have to add an extra check I think,
if we figure a library ought enforce any related checks,
so I'd likely be fine with other constraints or with no
constraint (at the library level).

S.

**Comment by ekr** [comment]
@martinthomson @davidben?

**Comment by martinthomson** [comment]
I can't see an attack that might arise from changing the public name.  It creates some interesting cross-provider interactions.

**Comment by ekr** [comment]
OK, so I'm just going to close this with no change.
