### ISSUE TITLE
Client behavior on wrong value in HRR extension

### ISSUE THREAD

**Issue by MikeBishop** [tlswg/draft-ietf-tls-esni#618]
In section 6.1.4, this note is found:

> [[OPEN ISSUE: Depending on what we do for issue#450, it may be appropriate to change the client behavior if the HRR extension is present but with the wrong value.]]

#450 is closed, but the text is still present and I didn't see a corresponding issue. Is there anything that needs to be done here, or should the note be removed?

**Comment by ekr** [comment]
Fixed.
