### ISSUE TITLE
Should we recommend how often to rotate keys?

### ISSUE THREAD

**Issue by ekr** [tlswg/draft-ietf-tls-esni#629]
From AD review.

See Section 10.10.5, which just says "frequently".

**Comment by seanturner** [comment]
At IETF 121, we decided to change "frequently" to "regularly".

**Comment by enygren** [comment]
Also highlighted in the chat was that we may wish to add security considerations on this:  too frequently reduces anonymity set, not frequently enough increases the amount of data that would be compromised in case of a private key compromise.
