### ISSUE TITLE
checksum and extension hashes

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-esni#64]
The hash used in the extension should use the same hash inputs as the checksum.  The difference here just makes using this harder.

**Comment by kazuho** [comment]
I support the change, if that makes people feel more comfortable about having the checksum field in ESNIKeys.

**Comment by ekr** [comment]
I'm not opposed, but it doesn't help as much as you might think, because
you need to compute the label with the cipher hash and not (necessarily)
with SHA-256.

**Comment by martinthomson** [comment]
So, if you take my suggestion in #142 (which I know @kazuho doesn't like, but we simply disagree about that), then you can identify the ESNI using a truncated hash that is calculated using the cipher hash because it only appears in the context of a handshake.  But that just suggests that this is either not-helpful because we chose not to do anything in #142, or it is not necessary because we did.  I'm OK closing this on that basis.

**Comment by chris-wood** [comment]
Checksum is now gone. Closing this issue. @martinthomson, thanks for filing it!
