### ISSUE TITLE
Limit this to DNS names

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-esni#68]
Extensibility failed for SNI, no point in repeating that failure.  This is less complex:

```
   struct {
       opaque domain_name<1..255>;
       opaque zeros[ESNIKeys.padded_length - length(sni)];
   } PaddedServerNameList;
```

**Comment by chris-wood** [comment]
Are there other ways we expect servers to select certificates? I can imagine a scenario where clients pin server leaf certificates, and hint servers to the right leaf certificate by sending the leaf SPKI hash in the SNI. Would we want to rule something like that out?
