### ISSUE TITLE
don't base 64 encode

### ISSUE THREAD

**Issue by mcmanus** [tlswg/draft-ietf-tls-esni#74]
dns records are 8 bit clean and rfc 6763 is an example of a TXT record carrying arbitrary data

**Comment by kazuho** [comment]
:+1:

Base64 is not only complication. It is a space overhead for a large object like ESNIKeys. Seeing corruption will be rare; we can detect them by validating the checksum and fallback to non-ESNI in such case.

FWIW, base64 was introduced in #18.

**Comment by ghedo** [comment]
This is solved in #73 which removes base64 with new ESNI RR type.

**Comment by chris-wood** [comment]
We only added this since TXT records were claimed to not work well with binary, per Christian’s suggestion. I’m fine either way.

**Comment by kazuho** [comment]
Thanks for the info. I found https://github.com/ekr/draft-rescorla-tls-esni/issues/14#issuecomment-388573921, in which @huitema asks:
> I really have two concerns, the maximum length and the char requirement. The latter may be an harder issue. For example, can I set a TXT record to contain binary data if I use Amazon's Route 53 service?

We know that we can store more than 128 octets in TXT record, and that we have a precedent that uses TXT to store binary data, as @mcmanus has pointed out.

Regarding configurability, my understanding is that RFC 1035 defines how binary TXT records can be specified in a zone file, and therefore many DNS server "softwares" support having such records. Googling also tells me that managed DNS services like Route 53 and Azure DNS provide the capability, although surprisingly they use different escape sequences ([Route 53](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#TXTFormat) uses `\` + 3 octal, [Azure](https://docs.microsoft.com/en-US/azure/dns/dns-faq) uses `\` + 3 decimal).

**Comment by chris-wood** [comment]
I do not think it’s a complication, and I’m not convinced space is an issue as per your comment above.

**Comment by mcmanus** [comment]
only tangentially related - @kazuho do you know why your examp1e.net txt record is broken into 127 char strings instead of 255? Is there a bug being worked around somewhere?

**Comment by kazuho** [comment]
@mcmanus Oh I did not notice that. I am using tinydns (of djbdns), and it seems like tinydns works that way (see https://github.com/abh/djbdns/blob/master/tinydns-data.c#L402).

**Comment by kazuho** [comment]
@chris-wood The issue about the size is that with base64 we might hit the 512-octet threshold when publishing keys of multiple strengths.

As an example, query for _esni.esni.examp1e.net currently returns a 186-byte response, which contains just secp256r1 key. If we add secp384r1 and secp521r1, I'd assume that the size will come near to 490 octets. In other words, for longer hostnames we will hit the 512-octet threshold if we publish three keys.

If we avoid the base64 encoding, we will have enough room to store 3 ECDH keys that can provide 128-, 192-, 256-bit-level security.

I do not think this argument is strong enough to prohibit the use of base64 for the following reasons:

* we will be using DoH / DNS over TLS between the client and the resolver
* we might be using DNS over UDP that has the 512-octet threshold between the resolver and the authoritative server, but we would want that to migrate to DNSSEC or something even better
* we might be just fine with publishing only two keys: X25519, X448

But it does make me prefer not to have the overhead of base64, if that is possible.

**Comment by chris-wood** [comment]
Fixed in #144.
