### ISSUE TITLE
Supporting multiple protocols text is slightly misleading

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#84]
Replace 

"It only affects connection routing, server certificate selection, and client certificate verification." 

with 

"It may affect connection routing, server certificate selection, and client certificate verification."

**Comment by yfdyh000** [comment]
https://ekr.github.io/draft-rescorla-tls-esni/draft-rescorla-tls-esni.html#rfc.section.7.2.8
It is relative to "This design has no impact on application layer protocol negotiation.", so "only" is more explicit.

**Comment by chris-wood** [comment]
This was fixed in #87 and I forgot to close.
